<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Creación de Excepciones Personalizadas</title>

    <link rel="alternate" href="https://campusempresa.com/es/ruby/creating-custom-exceptions" hreflang="es" />
    <link rel="alternate" href="https://campusempresa.com/es/ruby/creating-custom-exceptions" hreflang="x-default" />
	<link rel="alternate" href="https://campusempresa.com/ca/ruby/creating-custom-exceptions" hreflang="ca" />
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
	<link href="/css/site.css" rel="stylesheet">
	
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  	<script type="text/javascript" src="js/math_init.js"></script>
  	<script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js"></script>
  	<script type="text/javascript" src="/js/cookie.js"></script>
  	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body>
    <div id="content">
		<div id="header" class="container-xxl">
	<div class="row">
		<div class="col-8 p-0">
			<h1 class="m-0 p-0">
				<a href="/es/"><img src="/img/logo_header.png" style="visibility:hiddenxx;"></a>
			</h1>
		</div>
		<div class="col-4 p-0 text-end">
			<h2 id="main_title"><cite>Construyendo la sociedad de hoy y del mañana</cite></h2>
			<h3 id="main_subtitle"></h3>
		</div>
	</div>
</div>
<div class="container-xxl" style="margin-top: -1em;">
	<div class="row">
		<div class="col-12 p-0 m-0 text-end">
										<b id="lit_lang_es" class="px-2">ES</b>
				|
				<a href="/ca/ruby/creating-custom-exceptions" id="lnk_lang_ca" data-lang="ca" class="px-2">CA</a>
					</div>
	</div>
</div>
   <div class="top-bar container-fluid">
	<div class="container-xxl">
		<div class="row">
			<div class="col" id="left_menu">
				<a href="/es/objective">El Proyecto</a>
				<a href="/es/about">Sobre nosotros</a>
				<a href="/es/contribute">Contribuir</a>
				<a href="/es/donate">Donaciones</a>
				<a href="/es/licence">Licencia</a>
			</div>
		</div>
	</div>
   </div>

<div class="container-xxl" id="main_content">
	<div class="row">
		<div class="col-12 col-lg-8">
			<div id="nav1" class="navigation"></div>
			<div id="inner_content"><div class='row navigation'>
	<div class='col-4'>
					<a href='handling-exceptions'>&#x25C4;Manejo de Excepciones</a>
			</div>
	<div class='col-4 text-center'>
		<a href="./" class="title">Creación de Excepciones Personalizadas</a>
	</div>
	<div class='col-4 text-end'>
					<a href='ensuring-cleanup-with-ensure'>Asegurando la Limpieza con Ensure &#x25BA;</a>
			</div>
</div>
<div class='content'></div><h1>Introducción</h1>
<div class='content'><p>En Ruby, las excepciones se utilizan para manejar errores y otros eventos excepcionales. Aunque Ruby proporciona un conjunto rico de excepciones integradas, hay momentos en los que podrías necesitar crear tus propias excepciones personalizadas para manejar situaciones específicas en tu aplicación. Esta sección te guiará a través del proceso de creación y uso de excepciones personalizadas en Ruby.</p>
</div><h1>¿Por Qué Crear Excepciones Personalizadas?</h1>
<div class='content'><ul>
<li><strong>Especificidad</strong>: Las excepciones personalizadas te permiten manejar condiciones de error específicas de manera más precisa.</li>
<li><strong>Legibilidad</strong>: Hacen que tu código sea más legible y mantenible al indicar claramente qué tipo de error ha ocurrido.</li>
<li><strong>Separación de Responsabilidades</strong>: Las excepciones personalizadas ayudan a separar la lógica de manejo de errores de la lógica principal del código.</li>
</ul>
</div><h1>Creación de una Excepción Personalizada</h1>
<div class='content'><p>Crear una excepción personalizada en Ruby es sencillo. Simplemente necesitas definir una nueva clase que herede de la clase <code>StandardError</code> o de cualquier otra clase de excepción existente.</p>
</div><h2>Ejemplo Básico</h2>
<div class='content'><p>Aquí tienes un ejemplo básico de creación y uso de una excepción personalizada:</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("Y2xhc3MgTXlDdXN0b21FcnJvciA8IFN0YW5kYXJkRXJyb3IKZW5kCgpkZWYgcmlza3lfbWV0aG9kCiAgcmFpc2UgTXlDdXN0b21FcnJvciwgIsKhQWxnbyBzYWxpw7MgbWFsISIKZW5kCgpiZWdpbgogIHJpc2t5X21ldGhvZApyZXNjdWUgTXlDdXN0b21FcnJvciA9PiBlCiAgcHV0cyBlLm1lc3NhZ2UKZW5k"))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>class MyCustomError &lt; StandardError
end

def risky_method
  raise MyCustomError, &quot;&iexcl;Algo sali&oacute; mal!&quot;
end

begin
  risky_method
rescue MyCustomError =&gt; e
  puts e.message
end</pre></div><div class='content'></div><h2>Explicación</h2>
<div class='content'><ul>
<li><strong>Definición de la Excepción</strong>: <code>class MyCustomError &lt; StandardError</code> crea una nueva clase de excepción llamada <code>MyCustomError</code> que hereda de <code>StandardError</code>.</li>
<li><strong>Lanzamiento de la Excepción</strong>: <code>raise MyCustomError, &quot;¡Algo salió mal!&quot;</code> lanza la excepción personalizada con un mensaje de error específico.</li>
<li><strong>Manejo de la Excepción</strong>: El bloque <code>begin...rescue</code> se utiliza para manejar la excepción. Cuando se lanza <code>MyCustomError</code>, el bloque rescue la captura e imprime el mensaje de error.</li>
</ul>
</div><h1>Agregar Comportamiento Personalizado</h1>
<div class='content'><p>Puedes agregar comportamiento personalizado a tus clases de excepción definiendo métodos dentro de ellas.</p>
</div><h2>Ejemplo con Comportamiento Personalizado</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("Y2xhc3MgSW52YWxpZEFnZUVycm9yIDwgU3RhbmRhcmRFcnJvcgogIGF0dHJfcmVhZGVyIDphZ2UKCiAgZGVmIGluaXRpYWxpemUoYWdlKQogICAgQGFnZSA9IGFnZQogICAgc3VwZXIoIkVkYWQgaW52w6FsaWRhOiAje2FnZX0iKQogIGVuZAplbmQKCmRlZiB2YWxpZGF0ZV9hZ2UoYWdlKQogIHJhaXNlIEludmFsaWRBZ2VFcnJvci5uZXcoYWdlKSBzaSBsYSBlZGFkIGVzIDwgMCBvIGxhIGVkYWQgZXMgPiAxNTAKICBwdXRzICJMYSBlZGFkIGVzIHbDoWxpZGEuIgplbmQKCmJlZ2luCiAgdmFsaWRhdGVfYWdlKC01KQpyZXNjdWUgSW52YWxpZEFnZUVycm9yID0+IGUKICBwdXRzIGUubWVzc2FnZQogIHB1dHMgIkVkYWQgaW52w6FsaWRhIHByb3BvcmNpb25hZGE6ICN7ZS5hZ2V9IgplbmQ="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>class InvalidAgeError &lt; StandardError
  attr_reader :age

  def initialize(age)
    @age = age
    super(&quot;Edad inv&aacute;lida: #{age}&quot;)
  end
end

def validate_age(age)
  raise InvalidAgeError.new(age) si la edad es &lt; 0 o la edad es &gt; 150
  puts &quot;La edad es v&aacute;lida.&quot;
end

begin
  validate_age(-5)
rescue InvalidAgeError =&gt; e
  puts e.message
  puts &quot;Edad inv&aacute;lida proporcionada: #{e.age}&quot;
end</pre></div><div class='content'></div><h2>Explicación</h2>
<div class='content'><ul>
<li><strong>Inicialización Personalizada</strong>: El método <code>initialize</code> se sobrescribe para aceptar un parámetro <code>age</code> y establecer una variable de instancia.</li>
<li><strong>Mensaje Personalizado</strong>: <code>super(&quot;Edad inválida: #{age}&quot;)</code> llama al método <code>initialize</code> de la clase padre con un mensaje de error personalizado.</li>
<li><strong>Acceso a Datos Personalizados</strong>: La línea <code>attr_reader :age</code> crea un método getter para la variable de instancia <code>age</code>, permitiendo que sea accesible en el bloque rescue.</li>
</ul>
</div><h1>Mejores Prácticas</h1>
<div class='content'><ul>
<li><strong>Heredar de StandardError</strong>: Siempre hereda de <code>StandardError</code> o sus subclases para asegurar que tus excepciones personalizadas sean manejadas correctamente por el mecanismo de rescue predeterminado de Ruby.</li>
<li><strong>Nombres Significativos</strong>: Da a tus excepciones personalizadas nombres significativos que indiquen claramente el tipo de error.</li>
<li><strong>Mensajes Personalizados</strong>: Proporciona mensajes de error informativos para facilitar la depuración.</li>
</ul>
</div><h1>Conclusión</h1>
<div class='content'><p>Crear excepciones personalizadas en Ruby te permite manejar condiciones de error específicas de manera más efectiva y hacer que tu código sea más legible y mantenible. Siguiendo las mejores prácticas y agregando comportamiento personalizado cuando sea necesario, puedes crear mecanismos de manejo de errores robustos adaptados a las necesidades de tu aplicación.</p>
</div><div class='row navigation'>
	<div class='col-4'>
					<a href='handling-exceptions'>&#x25C4;Manejo de Excepciones</a>
			</div>
	<div class='col-4 text-center'>
		<a href="./" class="title">Creación de Excepciones Personalizadas</a>
	</div>
	<div class='col-4 text-end'>
					<a href='ensuring-cleanup-with-ensure'>Asegurando la Limpieza con Ensure &#x25BA;</a>
			</div>
</div>
</div>
		</div>
		<div class="col-12 col-lg-4 publi" id="div_publi">
			<h1>Publicidad</h1>
			<p>Este espacio está destinado a publicidad.</p>
			<p>Si quieres ser patrocinador, contáctanos para incluir enlaces en esta zona: <a href='mailto:admin@campusempresa.cat'>admin@campusempresa.cat</a></p>
			<p>¡Gracias por colaborar!</p>
		</div>
	</div>
</div>

   <div class="container-xxl my-3">
	<div class="row">
		<div class="col">
			<footer>&copy; Copyright 2024. Todos los derechos reservados</footer>
		</div>
	</div>
</div>	

<div id="cookies_adv" style="display:none;">
	Fem servir galetes per millorar la teva experiència d'ús i oferir continguts adaptats als teus interessos
    <a href="#" id="btn_accept_cookies" class="button">Entès!</a>
    <a href="/es/cookies">Més informació</a>
</div>	

	</div>    
</body>
</html>
