<!DOCTYPE html>
<html lang="ca">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestió d'Excepcions en Codi Asíncron</title>

    <link rel="alternate" href="https://campusempresa.com/es/csharp/exceptions-async" hreflang="es" />
    <link rel="alternate" href="https://campusempresa.com/es/csharp/exceptions-async" hreflang="x-default" />
	<link rel="alternate" href="https://campusempresa.com/ca/csharp/exceptions-async" hreflang="ca" />
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
	<link href="/css/site.css" rel="stylesheet">
	
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  	<script type="text/javascript" src="js/math_init.js"></script>
  	<script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js"></script>
  	<script type="text/javascript" src="/js/cookie.js"></script>
  	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body>
    <div id="content">
		<div id="header" class="container-xxl">
	<div class="row">
		<div class="col-8 p-0">
			<h1 class="m-0 p-0">
				<a href="/ca/"><img src="/img/logo_header.png" style="visibility:hiddenxx;"></a>
			</h1>
		</div>
		<div class="col-4 p-0 text-end">
			<h2 id="main_title"><cite>Construint la societat d'avui i del demà</cite></h2>
			<h3 id="main_subtitle"></h3>
		</div>
	</div>
</div>
<div class="container-xxl" style="margin-top: -1em;">
	<div class="row">
		<div class="col-12 p-0 m-0 text-end">
							<a href="/es/csharp/exceptions-async" id="lnk_lang_es" data-lang="es" class="px-2">ES</a></b>
				|
				<b id="lit_lang_ca" class="px-2">CA</b>
								</div>
	</div>
</div>
   <div class="top-bar container-fluid">
	<div class="container-xxl">
		<div class="row">
			<div class="col" id="left_menu">
				<a href="/ca/objective">El Projecte</a>
				<a href="/ca/about">Sobre nosaltres</a>
				<a href="/ca/contribute">Contribuir</a>
				<a href="/ca/donate">Donacions</a>
				<a href="/ca/licence">Llicència</a>
			</div>
		</div>
	</div>
   </div>

<div class="container-xxl" id="main_content">
	<div class="row">
		<div class="col-12 col-lg-8">
			<div id="nav1" class="navigation"></div>
			<div id="inner_content"><div class='row navigation'>
	<div class='col-4'>
					<a href='async-await'>&#x25C4;Async i Await</a>
			</div>
	<div class='col-4 text-center'>
		<a href="./" class="title">Gestió d'Excepcions en Codi Asíncron</a>
	</div>
	<div class='col-4 text-end'>
					<a href='introduction-databases'>Introducció a les Bases de Dades &#x25BA;</a>
			</div>
</div>
<div class='content'></div><h1>Introducció</h1>
<div class='content'><p>La gestió d'excepcions en codi asíncron pot ser un repte tant per a principiants com per a programadors avançats. Aquesta secció et guiarà a través dels conceptes bàsics de la gestió d'excepcions en codi asíncron, progressant cap a tècniques més avançades i millors pràctiques.</p>
</div><h1>Conceptes Clau</h1>
<div class='content'><ul>
<li><strong>Programació Asíncrona</strong>: Executar tasques en segon pla sense bloquejar el fil principal.</li>
<li><strong>Excepcions</strong>: Errors que ocorren durant l'execució d'un programa.</li>
<li><strong>Gestió d'Excepcions</strong>: Mecanismes per capturar i gestionar errors de manera elegant.</li>
</ul>
</div><h1>Gestió Bàsica d'Excepcions en Codi Asíncron</h1>
<div class='content'></div><h2>Ús de `try-catch` amb `async` i `await`</h2>
<div class='content'><p>Quan treballes amb mètodes asíncrons, pots utilitzar blocs <code>try-catch</code> per gestionar excepcions igual que en codi síncron.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("cHVibGljIGFzeW5jIFRhc2sgRXhhbXBsZU1ldGhvZEFzeW5jKCkKewogICAgdHJ5CiAgICB7CiAgICAgICAgYXdhaXQgVGFzay5SdW4oKCkgPT4geyB0aHJvdyBuZXcgSW52YWxpZE9wZXJhdGlvbkV4Y2VwdGlvbigiQW4gZXJyb3Igb2NjdXJyZWQuIik7IH0pOwogICAgfQogICAgY2F0Y2ggKEludmFsaWRPcGVyYXRpb25FeGNlcHRpb24gZXgpCiAgICB7CiAgICAgICAgQ29uc29sZS5Xcml0ZUxpbmUoJCJDYXVnaHQgYW4gZXhjZXB0aW9uOiB7ZXguTWVzc2FnZX0iKTsKICAgIH0KfQ=="))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>public async Task ExampleMethodAsync()
{
    try
    {
        await Task.Run(() =&gt; { throw new InvalidOperationException(&quot;An error occurred.&quot;); });
    }
    catch (InvalidOperationException ex)
    {
        Console.WriteLine($&quot;Caught an exception: {ex.Message}&quot;);
    }
}</pre></div><div class='content'><p>En aquest exemple:</p>
<ul>
<li><code>Task.Run</code> s'utilitza per simular una operació asíncrona que llança una excepció.</li>
<li>El bloc <code>try-catch</code> captura la <code>InvalidOperationException</code> i la gestiona imprimint un missatge a la consola.</li>
</ul>
</div><h1>Gestió d'Excepcions en Múltiples Mètodes Asíncrons</h1>
<div class='content'></div><h2>Propagació d'Excepcions</h2>
<div class='content'><p>Les excepcions en mètodes asíncrons poden propagar-se cap amunt en la pila de crides. Pots capturar-les a un nivell superior si cal.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("cHVibGljIGFzeW5jIFRhc2sgTWV0aG9kMUFzeW5jKCkKewogICAgYXdhaXQgTWV0aG9kMkFzeW5jKCk7Cn0KCnB1YmxpYyBhc3luYyBUYXNrIE1ldGhvZDJBc3luYygpCnsKICAgIHRocm93IG5ldyBJbnZhbGlkT3BlcmF0aW9uRXhjZXB0aW9uKCJBbiBlcnJvciBvY2N1cnJlZCBpbiBNZXRob2QyQXN5bmMuIik7Cn0KCnB1YmxpYyBhc3luYyBUYXNrIE1haW5NZXRob2RBc3luYygpCnsKICAgIHRyeQogICAgewogICAgICAgIGF3YWl0IE1ldGhvZDFBc3luYygpOwogICAgfQogICAgY2F0Y2ggKEludmFsaWRPcGVyYXRpb25FeGNlcHRpb24gZXgpCiAgICB7CiAgICAgICAgQ29uc29sZS5Xcml0ZUxpbmUoJCJDYXVnaHQgYW4gZXhjZXB0aW9uOiB7ZXguTWVzc2FnZX0iKTsKICAgIH0KfQ=="))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>public async Task Method1Async()
{
    await Method2Async();
}

public async Task Method2Async()
{
    throw new InvalidOperationException(&quot;An error occurred in Method2Async.&quot;);
}

public async Task MainMethodAsync()
{
    try
    {
        await Method1Async();
    }
    catch (InvalidOperationException ex)
    {
        Console.WriteLine($&quot;Caught an exception: {ex.Message}&quot;);
    }
}</pre></div><div class='content'><p>En aquest exemple:</p>
<ul>
<li><code>Method2Async</code> llança una excepció.</li>
<li><code>Method1Async</code> crida <code>Method2Async</code> però no gestiona l'excepció.</li>
<li><code>MainMethodAsync</code> crida <code>Method1Async</code> i captura l'excepció propagada.</li>
</ul>
</div><h1>Gestió Avançada d'Excepcions</h1>
<div class='content'></div><h2>Ús de `Task.WhenAll` amb Gestió d'Excepcions</h2>
<div class='content'><p>Quan executes múltiples tasques simultàniament, pots utilitzar <code>Task.WhenAll</code> per esperar que totes les tasques es completin i gestionar les excepcions.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("cHVibGljIGFzeW5jIFRhc2sgUnVuTXVsdGlwbGVUYXNrc0FzeW5jKCkKewogICAgdmFyIHRhc2sxID0gVGFzay5SdW4oKCkgPT4geyB0aHJvdyBuZXcgSW52YWxpZE9wZXJhdGlvbkV4Y2VwdGlvbigiVGFzazEgZmFpbGVkLiIpOyB9KTsKICAgIHZhciB0YXNrMiA9IFRhc2suUnVuKCgpID0+IHsgdGhyb3cgbmV3IEludmFsaWRPcGVyYXRpb25FeGNlcHRpb24oIlRhc2syIGZhaWxlZC4iKTsgfSk7CgogICAgdHJ5CiAgICB7CiAgICAgICAgYXdhaXQgVGFzay5XaGVuQWxsKHRhc2sxLCB0YXNrMik7CiAgICB9CiAgICBjYXRjaCAoRXhjZXB0aW9uIGV4KQogICAgewogICAgICAgIGZvcmVhY2ggKHZhciBpbm5lckV4Y2VwdGlvbiBpbiBleC5Jbm5lckV4Y2VwdGlvbnMpCiAgICAgICAgewogICAgICAgICAgICBDb25zb2xlLldyaXRlTGluZSgkIkNhdWdodCBhbiBleGNlcHRpb246IHtpbm5lckV4Y2VwdGlvbi5NZXNzYWdlfSIpOwogICAgICAgIH0KICAgIH0KfQ=="))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>public async Task RunMultipleTasksAsync()
{
    var task1 = Task.Run(() =&gt; { throw new InvalidOperationException(&quot;Task1 failed.&quot;); });
    var task2 = Task.Run(() =&gt; { throw new InvalidOperationException(&quot;Task2 failed.&quot;); });

    try
    {
        await Task.WhenAll(task1, task2);
    }
    catch (Exception ex)
    {
        foreach (var innerException in ex.InnerExceptions)
        {
            Console.WriteLine($&quot;Caught an exception: {innerException.Message}&quot;);
        }
    }
}</pre></div><div class='content'><p>En aquest exemple:</p>
<ul>
<li>Es creen dues tasques, ambdues llancen excepcions.</li>
<li><code>Task.WhenAll</code> espera que ambdues tasques es completin.</li>
<li>El bloc <code>catch</code> itera a través de <code>InnerExceptions</code> per gestionar cada excepció individualment.</li>
</ul>
</div><h2>Ús de la Propietat `Task.Exception`</h2>
<div class='content'><p>També pots accedir a la propietat <code>Exception</code> d'una <code>Task</code> per gestionar excepcions després que la tasca s'hagi completat.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("cHVibGljIGFzeW5jIFRhc2sgSGFuZGxlVGFza0V4Y2VwdGlvbkFzeW5jKCkKewogICAgdmFyIHRhc2sgPSBUYXNrLlJ1bigoKSA9PiB7IHRocm93IG5ldyBJbnZhbGlkT3BlcmF0aW9uRXhjZXB0aW9uKCJUYXNrIGZhaWxlZC4iKTsgfSk7CgogICAgdHJ5CiAgICB7CiAgICAgICAgYXdhaXQgdGFzazsKICAgIH0KICAgIGNhdGNoCiAgICB7CiAgICAgICAgaWYgKHRhc2suRXhjZXB0aW9uICE9IG51bGwpCiAgICAgICAgewogICAgICAgICAgICBmb3JlYWNoICh2YXIgaW5uZXJFeGNlcHRpb24gaW4gdGFzay5FeGNlcHRpb24uSW5uZXJFeGNlcHRpb25zKQogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICBDb25zb2xlLldyaXRlTGluZSgkIkNhdWdodCBhbiBleGNlcHRpb246IHtpbm5lckV4Y2VwdGlvbi5NZXNzYWdlfSIpOwogICAgICAgICAgICB9CiAgICAgICAgfQogICAgfQp9"))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>public async Task HandleTaskExceptionAsync()
{
    var task = Task.Run(() =&gt; { throw new InvalidOperationException(&quot;Task failed.&quot;); });

    try
    {
        await task;
    }
    catch
    {
        if (task.Exception != null)
        {
            foreach (var innerException in task.Exception.InnerExceptions)
            {
                Console.WriteLine($&quot;Caught an exception: {innerException.Message}&quot;);
            }
        }
    }
}</pre></div><div class='content'><p>En aquest exemple:</p>
<ul>
<li>Es crea una tasca que llança una excepció.</li>
<li>El bloc <code>catch</code> comprova la propietat <code>Exception</code> de la tasca i gestiona cada excepció interna.</li>
</ul>
</div><h1>Conclusió</h1>
<div class='content'><p>La gestió d'excepcions en codi asíncron és crucial per construir aplicacions robustes i fiables. Entenent i aplicant les tècniques discutides en aquesta secció, pots gestionar efectivament els errors en els teus mètodes asíncrons. Recorda:</p>
<ul>
<li>Utilitza blocs <code>try-catch</code> per gestionar excepcions en mètodes asíncrons.</li>
<li>Propaga excepcions a nivells superiors quan sigui necessari.</li>
<li>Utilitza <code>Task.WhenAll</code> i la propietat <code>Exception</code> de les tasques per a escenaris avançats de gestió d'excepcions.</li>
</ul>
<p>Amb aquestes eines i tècniques, estaràs ben preparat per gestionar excepcions en el teu codi asíncron en C#, assegurant que les teves aplicacions funcionin sense problemes fins i tot quan es produeixin errors inesperats.</p>
</div><div class='row navigation'>
	<div class='col-4'>
					<a href='async-await'>&#x25C4;Async i Await</a>
			</div>
	<div class='col-4 text-center'>
		<a href="./" class="title">Gestió d'Excepcions en Codi Asíncron</a>
	</div>
	<div class='col-4 text-end'>
					<a href='introduction-databases'>Introducció a les Bases de Dades &#x25BA;</a>
			</div>
</div>
</div>
		</div>
		<div class="col-12 col-lg-4 publi" id="div_publi">
			<h1>Publicitat</h1>
			<p>Aquest espai està destinat a publicitat.</p>
			<p>Si vols ser patrocinador, contacta amb nosaltres per incloure enllaços en aquesta zona: <a href='mailto:admin@campusempresa.cat'>admin@campusempresa.cat</a></p>
			<p>Gràcies per col·laborar!</p>
		</div>
	</div>
</div>

   <div class="container-xxl my-3">
	<div class="row">
		<div class="col">
			<footer>&copy; Copyright 2024. Tots els drets reservats</footer>
		</div>
	</div>
</div>	

<div id="cookies_adv" style="display:none;">
	Fem servir galetes per millorar la teva experiència d'ús i oferir continguts adaptats als teus interessos
    <a href="#" id="btn_accept_cookies" class="button">Entès!</a>
    <a href="/ca/cookies">Més informació</a>
</div>	

	</div>    
</body>
</html>
