<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manejo de Errores con try-catch</title>

    <link rel="alternate" href="https://campusempresa.com/mod/javascript/02-04-error-handling" hreflang="es" />
	<link rel="alternate" href="https://campusempresa.cat/mod/javascript/02-04-error-handling" hreflang="ca" />
	<link rel="alternate" href="https://enterprisecampus.net/mod/javascript/02-04-error-handling" hreflang="en" />
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
	<link href="/css/site.css" rel="stylesheet">
	
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  	<script type="text/javascript" src="js/math_init.js"></script>
  	<script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js"></script>
  	<script type="text/javascript" src="/js/cookie.js"></script>
  	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body >
    <div id="content">
		<div id="header" class="container-xxl">
	<div class="row">
		<div class="col-12 col-md-8 p-0">
			<h1 class="m-0 p-0">
				<a href="/"><img src="/img/logo_header.png"></a>
			</h1>
		</div>
		<div class="col-12 col-md-4 p-0 text-end">
			<h2 id="main_title"><cite>Construyendo la sociedad de hoy y del mañana</cite></h2>
			<h3 id="main_subtitle"></h3>
		</div>
	</div>
</div>
<div class="container-xxl" style="margin-top: -1em;">
	<div class="row">
		<div class="col-12 p-0 m-0 text-end">
										<a href="https://enterprisecampus.net/mod/javascript/02-04-error-handling" class="px-2">EN</a></b>
				|
				<b class="px-2">ES</b>
				|
				<a href="https://campusempresa.cat/mod/javascript/02-04-error-handling" class="px-2">CA</a>
								</div>
	</div>
</div>
   <div class="top-bar container-fluid">
	<div class="container-xxl">
		<div class="row">
			<div class="col" id="left_menu">
				<a href="/objective">El Proyecto</a>
				<a href="/about">Sobre nosotros</a>
				<a href="/contribute">Contribuir</a>
				<a href="/donate">Donaciones</a>
				<a href="/licence">Licencia</a>
			</div>
		</div>
	</div>
   </div>

<div class="container-xxl" id="main_content">
	<div class="row">
		<div class="col-12 col-lg-8">
			<div id="nav1" class="navigation"></div>
			<div id="inner_content">
								<div class='row navigation'>
	<div class='col-2'>
					<a href='02-03-switch-statements' title="Sentencias Switch">&#x25C4;Anterior</a>
			</div>
	<div class='col-8 text-center'>
					<a href="./"><h2 style="text-decoration:underline">Manejo de Errores con try-catch</h2></a>
			</div>
	<div class='col-2 text-end'>
					<a href='03-01-defining-calling-functions' title="Definición y Llamada de Funciones">Siguiente &#x25BA;</a>
			</div>
</div>
<div class='content'><p>El manejo de errores es una parte crucial del desarrollo de software, ya que permite a los desarrolladores anticipar y gestionar posibles fallos en el código de manera controlada. En JavaScript, el manejo de errores se realiza principalmente mediante las sentencias <code>try</code>, <code>catch</code>, <code>finally</code> y <code>throw</code>.</p>
</div><h1>Conceptos Clave</h1>
<div class='content'><ol>
<li><strong>try</strong>: Bloque de código que se ejecuta y donde se pueden producir errores.</li>
<li><strong>catch</strong>: Bloque de código que se ejecuta si se produce un error en el bloque <code>try</code>.</li>
<li><strong>finally</strong>: Bloque de código que se ejecuta siempre, independientemente de si se produjo un error o no.</li>
<li><strong>throw</strong>: Permite lanzar un error de manera manual.</li>
</ol>
</div><h1>Estructura Básica</h1>
<div class='content'><p>La estructura básica de manejo de errores en JavaScript es la siguiente:</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("dHJ5IHsKICAgIC8vIEPDs2RpZ28gcXVlIHB1ZWRlIHByb2R1Y2lyIHVuIGVycm9yCn0gY2F0Y2ggKGVycm9yKSB7CiAgICAvLyBDw7NkaWdvIHF1ZSBzZSBlamVjdXRhIHNpIHNlIHByb2R1Y2UgdW4gZXJyb3IKfSBmaW5hbGx5IHsKICAgIC8vIEPDs2RpZ28gcXVlIHNlIGVqZWN1dGEgc2llbXByZSwgaW5kZXBlbmRpZW50ZW1lbnRlIGRlIHNpIHNlIHByb2R1am8gdW4gZXJyb3IgbyBubwp9"))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>try {
    // C&oacute;digo que puede producir un error
} catch (error) {
    // C&oacute;digo que se ejecuta si se produce un error
} finally {
    // C&oacute;digo que se ejecuta siempre, independientemente de si se produjo un error o no
}</pre></div><div class='content'></div><h1>Ejemplo Práctico</h1>
<div class='content'><p>Vamos a ver un ejemplo práctico para entender cómo funciona el manejo de errores en JavaScript.</p>
</div><h2>Ejemplo 1: Manejo Básico de Errores</h2>
<div class='content'></div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("dHJ5IHsKICAgIGxldCByZXN1bHQgPSAxMCAvIDA7IC8vIEVzdG8gbm8gcHJvZHVjaXLDoSB1biBlcnJvciBlbiBKYXZhU2NyaXB0LCBwZXJvIGVzIHVuIGVqZW1wbG8gZGUgY8OzZGlnbyBxdWUgcG9kcsOtYSBmYWxsYXIKICAgIGNvbnNvbGUubG9nKHJlc3VsdCk7Cn0gY2F0Y2ggKGVycm9yKSB7CiAgICBjb25zb2xlLmxvZygiU2UgaGEgcHJvZHVjaWRvIHVuIGVycm9yOiAiICsgZXJyb3IubWVzc2FnZSk7Cn0gZmluYWxseSB7CiAgICBjb25zb2xlLmxvZygiRXN0ZSBibG9xdWUgc2UgZWplY3V0YSBzaWVtcHJlLiIpOwp9"))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>try {
    let result = 10 / 0; // Esto no producir&aacute; un error en JavaScript, pero es un ejemplo de c&oacute;digo que podr&iacute;a fallar
    console.log(result);
} catch (error) {
    console.log(&quot;Se ha producido un error: &quot; + error.message);
} finally {
    console.log(&quot;Este bloque se ejecuta siempre.&quot;);
}</pre></div><div class='content'></div><h2>Explicación</h2>
<div class='content'><ol>
<li><strong>try</strong>: Intentamos ejecutar el código que podría producir un error.</li>
<li><strong>catch</strong>: Si se produce un error, se captura y se maneja en este bloque.</li>
<li><strong>finally</strong>: Este bloque se ejecuta siempre, independientemente de si se produjo un error o no.</li>
</ol>
</div><h2>Ejemplo 2: Lanzar un Error Manualmente</h2>
<div class='content'></div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("ZnVuY3Rpb24gZGl2aWRpcihhLCBiKSB7CiAgICBpZiAoYiA9PT0gMCkgewogICAgICAgIHRocm93IG5ldyBFcnJvcigiTm8gc2UgcHVlZGUgZGl2aWRpciBwb3IgY2VybyIpOwogICAgfQogICAgcmV0dXJuIGEgLyBiOwp9Cgp0cnkgewogICAgbGV0IHJlc3VsdGFkbyA9IGRpdmlkaXIoMTAsIDApOwogICAgY29uc29sZS5sb2cocmVzdWx0YWRvKTsKfSBjYXRjaCAoZXJyb3IpIHsKICAgIGNvbnNvbGUubG9nKCJTZSBoYSBwcm9kdWNpZG8gdW4gZXJyb3I6ICIgKyBlcnJvci5tZXNzYWdlKTsKfSBmaW5hbGx5IHsKICAgIGNvbnNvbGUubG9nKCJPcGVyYWNpw7NuIGRlIGRpdmlzacOzbiBjb21wbGV0YWRhLiIpOwp9"))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>function dividir(a, b) {
    if (b === 0) {
        throw new Error(&quot;No se puede dividir por cero&quot;);
    }
    return a / b;
}

try {
    let resultado = dividir(10, 0);
    console.log(resultado);
} catch (error) {
    console.log(&quot;Se ha producido un error: &quot; + error.message);
} finally {
    console.log(&quot;Operaci&oacute;n de divisi&oacute;n completada.&quot;);
}</pre></div><div class='content'></div><h2>Explicación</h2>
<div class='content'><ol>
<li><strong>throw</strong>: Lanzamos un error manualmente si <code>b</code> es igual a 0.</li>
<li><strong>try</strong>: Intentamos ejecutar la función <code>dividir</code>.</li>
<li><strong>catch</strong>: Si se lanza un error, se captura y se maneja en este bloque.</li>
<li><strong>finally</strong>: Este bloque se ejecuta siempre, independientemente de si se produjo un error o no.</li>
</ol>
</div><h1>Ejercicios Prácticos</h1>
<div class='content'></div><h2>Ejercicio 1: Manejo de Errores en Conversión de Tipos</h2>
<div class='content'><p>Escribe una función que convierta una cadena a un número. Si la cadena no puede ser convertida, lanza un error y manéjalo adecuadamente.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("ZnVuY3Rpb24gY29udmVydGlyQUNhZGVuYShudW1lcm8pIHsKICAgIGlmIChpc05hTihudW1lcm8pKSB7CiAgICAgICAgdGhyb3cgbmV3IEVycm9yKCJFbCB2YWxvciBwcm9wb3JjaW9uYWRvIG5vIGVzIHVuIG7Dum1lcm8iKTsKICAgIH0KICAgIHJldHVybiBOdW1iZXIobnVtZXJvKTsKfQoKdHJ5IHsKICAgIGxldCBudW1lcm8gPSBjb252ZXJ0aXJBQ2FkZW5hKCJhYmMiKTsKICAgIGNvbnNvbGUubG9nKG51bWVybyk7Cn0gY2F0Y2ggKGVycm9yKSB7CiAgICBjb25zb2xlLmxvZygiU2UgaGEgcHJvZHVjaWRvIHVuIGVycm9yOiAiICsgZXJyb3IubWVzc2FnZSk7Cn0gZmluYWxseSB7CiAgICBjb25zb2xlLmxvZygiQ29udmVyc2nDs24gY29tcGxldGFkYS4iKTsKfQ=="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>function convertirACadena(numero) {
    if (isNaN(numero)) {
        throw new Error(&quot;El valor proporcionado no es un n&uacute;mero&quot;);
    }
    return Number(numero);
}

try {
    let numero = convertirACadena(&quot;abc&quot;);
    console.log(numero);
} catch (error) {
    console.log(&quot;Se ha producido un error: &quot; + error.message);
} finally {
    console.log(&quot;Conversi&oacute;n completada.&quot;);
}</pre></div><div class='content'></div><h2>Ejercicio 2: Manejo de Errores en Acceso a Propiedades de Objetos</h2>
<div class='content'><p>Escribe una función que acceda a una propiedad de un objeto. Si la propiedad no existe, lanza un error y manéjalo adecuadamente.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("ZnVuY3Rpb24gb2J0ZW5lclByb3BpZWRhZChvYmpldG8sIHByb3BpZWRhZCkgewogICAgaWYgKCFvYmpldG8uaGFzT3duUHJvcGVydHkocHJvcGllZGFkKSkgewogICAgICAgIHRocm93IG5ldyBFcnJvcigiTGEgcHJvcGllZGFkIG5vIGV4aXN0ZSBlbiBlbCBvYmpldG8iKTsKICAgIH0KICAgIHJldHVybiBvYmpldG9bcHJvcGllZGFkXTsKfQoKdHJ5IHsKICAgIGxldCBwZXJzb25hID0geyBub21icmU6ICJKdWFuIiwgZWRhZDogMzAgfTsKICAgIGxldCB2YWxvciA9IG9idGVuZXJQcm9waWVkYWQocGVyc29uYSwgImFwZWxsaWRvIik7CiAgICBjb25zb2xlLmxvZyh2YWxvcik7Cn0gY2F0Y2ggKGVycm9yKSB7CiAgICBjb25zb2xlLmxvZygiU2UgaGEgcHJvZHVjaWRvIHVuIGVycm9yOiAiICsgZXJyb3IubWVzc2FnZSk7Cn0gZmluYWxseSB7CiAgICBjb25zb2xlLmxvZygiQWNjZXNvIGEgcHJvcGllZGFkIGNvbXBsZXRhZG8uIik7Cn0="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>function obtenerPropiedad(objeto, propiedad) {
    if (!objeto.hasOwnProperty(propiedad)) {
        throw new Error(&quot;La propiedad no existe en el objeto&quot;);
    }
    return objeto[propiedad];
}

try {
    let persona = { nombre: &quot;Juan&quot;, edad: 30 };
    let valor = obtenerPropiedad(persona, &quot;apellido&quot;);
    console.log(valor);
} catch (error) {
    console.log(&quot;Se ha producido un error: &quot; + error.message);
} finally {
    console.log(&quot;Acceso a propiedad completado.&quot;);
}</pre></div><div class='content'></div><h1>Resumen</h1>
<div class='content'><p>En esta sección, hemos aprendido cómo manejar errores en JavaScript utilizando las sentencias <code>try</code>, <code>catch</code>, <code>finally</code> y <code>throw</code>. Hemos visto ejemplos prácticos y ejercicios para reforzar los conceptos aprendidos. El manejo adecuado de errores es esencial para crear aplicaciones robustas y confiables.</p>
<p>En el siguiente módulo, exploraremos las funciones en JavaScript, incluyendo cómo definirlas, llamarlas y trabajar con parámetros y valores de retorno.</p>
</div><div class='row navigation'>
	<div class='col-2'>
					<a href='02-03-switch-statements' title="Sentencias Switch">&#x25C4;Anterior</a>
			</div>
	<div class='col-8 text-center'>
			</div>
	<div class='col-2 text-end'>
					<a href='03-01-defining-calling-functions' title="Definición y Llamada de Funciones">Siguiente &#x25BA;</a>
			</div>
</div>

			</div>
		</div>
		<div class="col-12 col-lg-4 publi" id="div_publi">
			<h1>Publicidad</h1>
			<p>Este espacio está destinado a publicidad.</p>
			<p>Si quieres ser patrocinador, contáctanos para incluir enlaces en esta zona: <a href='mailto:admin@campusempresa.cat'>admin@campusempresa.cat</a></p>
			<p>¡Gracias por colaborar!</p>
		</div>
	</div>
</div>

   <div class="container-xxl my-3">
	<div class="row">
		<div class="col">
			<footer>&copy; Copyright 2024. Todos los derechos reservados</footer>
		</div>
	</div>
</div>	

<div id="cookies_adv" style="display:none;">
	Fem servir galetes per millorar la teva experiència d'ús i oferir continguts adaptats als teus interessos
    <a href="#" id="btn_accept_cookies" class="button">Aceptar</a>
    <a href="/cookies">Mas información</a>
</div>	

	</div>    
</body>
</html>
