<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Panic y Recover</title>

    <link rel="alternate" href="https://campusempresa.com/mod/go/04-03-panic-and-recover" hreflang="es" />
	<link rel="alternate" href="https://campusempresa.cat/mod/go/04-03-panic-and-recover" hreflang="ca" />
	<link rel="alternate" href="https://enterprisecampus.net/mod/go/04-03-panic-and-recover" hreflang="en" />
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
	<link href="/css/site.css" rel="stylesheet">
	
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  	<script type="text/javascript" src="js/math_init.js"></script>
  	<script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js"></script>
  	<script type="text/javascript" src="/js/cookie.js"></script>
  	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body >
    <div id="content">
		<div id="header" class="container-xxl">
	<div class="row">
		<div class="col-8 p-0">
			<h1 class="m-0 p-0">
				<a href="/"><img src="/img/logo_header.png"></a>
			</h1>
		</div>
		<div class="col-4 p-0 text-end">
			<h2 id="main_title"><cite>Construyendo la sociedad de hoy y del mañana</cite></h2>
			<h3 id="main_subtitle"></h3>
		</div>
	</div>
</div>
<div class="container-xxl" style="margin-top: -1em;">
	<div class="row">
		<div class="col-12 p-0 m-0 text-end">
										<a href="https://enterprisecampus.net/mod/go/04-03-panic-and-recover" class="px-2">EN</a></b>
				|
				<b class="px-2">ES</b>
				|
				<a href="https://campusempresa.cat/mod/go/04-03-panic-and-recover" class="px-2">CA</a>
								</div>
	</div>
</div>
   <div class="top-bar container-fluid">
	<div class="container-xxl">
		<div class="row">
			<div class="col" id="left_menu">
				<a href="/objective">El Proyecto</a>
				<a href="/about">Sobre nosotros</a>
				<a href="/contribute">Contribuir</a>
				<a href="/donate">Donaciones</a>
				<a href="/licence">Licencia</a>
			</div>
		</div>
	</div>
   </div>

<div class="container-xxl" id="main_content">
	<div class="row">
		<div class="col-12 col-lg-8">
			<div id="nav1" class="navigation"></div>
			<div id="inner_content">
								<div class='row navigation'>
	<div class='col-2'>
					<a href='04-02-custom-errors' title="Errores Personalizados">&#x25C4;Anterior</a>
			</div>
	<div class='col-8 text-center'>
					<a href="./"><h2 style="text-decoration:underline">Panic y Recover</h2></a>
			</div>
	<div class='col-2 text-end'>
					<a href='05-01-goroutines' title="Goroutines">Siguiente &#x25BA;</a>
			</div>
</div>
<div class='content'><p>En este tema, aprenderemos sobre dos mecanismos importantes en Go para el manejo de errores y situaciones excepcionales: <code>panic</code> y <code>recover</code>. Estos mecanismos permiten manejar errores de una manera controlada y segura, especialmente en situaciones críticas donde la ejecución del programa no puede continuar normalmente.</p>
</div><h1>¿Qué es `panic`?</h1>
<div class='content'><p><code>panic</code> es una función incorporada en Go que se utiliza para detener la ejecución normal de un programa. Cuando se llama a <code>panic</code>, el programa imprime un mensaje de error y comienza a desenrollar la pila de llamadas, ejecutando las funciones <code>defer</code> en el camino. Finalmente, el programa se detiene.</p>
</div><h2>Ejemplo de `panic`</h2>
<div class='content'></div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("cGFja2FnZSBtYWluCgppbXBvcnQgImZtdCIKCmZ1bmMgbWFpbigpIHsKICAgIGZtdC5QcmludGxuKCJJbmljaW8gZGVsIHByb2dyYW1hIikKICAgIGNhdXNlUGFuaWMoKQogICAgZm10LlByaW50bG4oIkZpbiBkZWwgcHJvZ3JhbWEiKSAvLyBFc3RhIGzDrW5lYSBubyBzZSBlamVjdXRhcsOhCn0KCmZ1bmMgY2F1c2VQYW5pYygpIHsKICAgIGZtdC5QcmludGxuKCJBbnRlcyBkZWwgcMOhbmljbyIpCiAgICBwYW5pYygiwqFBbGdvIHNhbGnDsyBtYWwhIikKICAgIGZtdC5QcmludGxuKCJEZXNwdcOpcyBkZWwgcMOhbmljbyIpIC8vIEVzdGEgbMOtbmVhIG5vIHNlIGVqZWN1dGFyw6EKfQ=="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>package main

import &quot;fmt&quot;

func main() {
    fmt.Println(&quot;Inicio del programa&quot;)
    causePanic()
    fmt.Println(&quot;Fin del programa&quot;) // Esta l&iacute;nea no se ejecutar&aacute;
}

func causePanic() {
    fmt.Println(&quot;Antes del p&aacute;nico&quot;)
    panic(&quot;&iexcl;Algo sali&oacute; mal!&quot;)
    fmt.Println(&quot;Despu&eacute;s del p&aacute;nico&quot;) // Esta l&iacute;nea no se ejecutar&aacute;
}</pre></div><div class='content'><p><strong>Explicación:</strong></p>
<ul>
<li>La función <code>causePanic</code> llama a <code>panic</code> con un mensaje de error.</li>
<li>Una vez que se llama a <code>panic</code>, el programa imprime el mensaje de error y comienza a desenrollar la pila de llamadas.</li>
<li>Las líneas de código después de <code>panic</code> no se ejecutan.</li>
</ul>
</div><h1>¿Qué es `recover`?</h1>
<div class='content'><p><code>recover</code> es una función incorporada que permite recuperar el control de un programa que ha entrado en pánico. <code>recover</code> solo funciona dentro de una función <code>defer</code>. Si se llama a <code>recover</code> y no hay un pánico en curso, <code>recover</code> devuelve <code>nil</code>.</p>
</div><h2>Ejemplo de `recover`</h2>
<div class='content'></div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("cGFja2FnZSBtYWluCgppbXBvcnQgImZtdCIKCmZ1bmMgbWFpbigpIHsKICAgIGZtdC5QcmludGxuKCJJbmljaW8gZGVsIHByb2dyYW1hIikKICAgIHNhZmVGdW5jdGlvbigpCiAgICBmbXQuUHJpbnRsbigiRmluIGRlbCBwcm9ncmFtYSIpIC8vIEVzdGEgbMOtbmVhIHNlIGVqZWN1dGFyw6EKfQoKZnVuYyBzYWZlRnVuY3Rpb24oKSB7CiAgICBkZWZlciBmdW5jKCkgewogICAgICAgIGlmIHIgOj0gcmVjb3ZlcigpOyByICE9IG5pbCB7CiAgICAgICAgICAgIGZtdC5QcmludGxuKCJSZWN1cGVyYWRvIGRlbCBww6FuaWNvOiIsIHIpCiAgICAgICAgfQogICAgfSgpCiAgICBjYXVzZVBhbmljKCkKICAgIGZtdC5QcmludGxuKCJEZXNwdcOpcyBkZSBjYXVzZVBhbmljIikgLy8gRXN0YSBsw61uZWEgbm8gc2UgZWplY3V0YXLDoQp9CgpmdW5jIGNhdXNlUGFuaWMoKSB7CiAgICBmbXQuUHJpbnRsbigiQW50ZXMgZGVsIHDDoW5pY28iKQogICAgcGFuaWMoIsKhQWxnbyBzYWxpw7MgbWFsISIpCiAgICBmbXQuUHJpbnRsbigiRGVzcHXDqXMgZGVsIHDDoW5pY28iKSAvLyBFc3RhIGzDrW5lYSBubyBzZSBlamVjdXRhcsOhCn0="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>package main

import &quot;fmt&quot;

func main() {
    fmt.Println(&quot;Inicio del programa&quot;)
    safeFunction()
    fmt.Println(&quot;Fin del programa&quot;) // Esta l&iacute;nea se ejecutar&aacute;
}

func safeFunction() {
    defer func() {
        if r := recover(); r != nil {
            fmt.Println(&quot;Recuperado del p&aacute;nico:&quot;, r)
        }
    }()
    causePanic()
    fmt.Println(&quot;Despu&eacute;s de causePanic&quot;) // Esta l&iacute;nea no se ejecutar&aacute;
}

func causePanic() {
    fmt.Println(&quot;Antes del p&aacute;nico&quot;)
    panic(&quot;&iexcl;Algo sali&oacute; mal!&quot;)
    fmt.Println(&quot;Despu&eacute;s del p&aacute;nico&quot;) // Esta l&iacute;nea no se ejecutar&aacute;
}</pre></div><div class='content'><p><strong>Explicación:</strong></p>
<ul>
<li>La función <code>safeFunction</code> utiliza <code>defer</code> para definir una función anónima que llama a <code>recover</code>.</li>
<li>Si <code>causePanic</code> provoca un pánico, <code>recover</code> captura el pánico y permite que el programa continúe ejecutándose.</li>
<li>El mensaje &quot;Recuperado del pánico&quot; se imprime, y el programa no se detiene abruptamente.</li>
</ul>
</div><h1>Ejercicio Práctico</h1>
<div class='content'></div><h2>Ejercicio 1: Manejo de Pánico en una Función</h2>
<div class='content'><p>Escribe una función llamada <code>divide</code> que tome dos enteros y devuelva el resultado de la división. Si el divisor es cero, la función debe provocar un pánico. Luego, escribe una función <code>safeDivide</code> que utilice <code>recover</code> para manejar el pánico y devolver un error en lugar de detener el programa.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("cGFja2FnZSBtYWluCgppbXBvcnQgKAogICAgImVycm9ycyIKICAgICJmbXQiCikKCmZ1bmMgbWFpbigpIHsKICAgIHJlc3VsdCwgZXJyIDo9IHNhZmVEaXZpZGUoMTAsIDApCiAgICBpZiBlcnIgIT0gbmlsIHsKICAgICAgICBmbXQuUHJpbnRsbigiRXJyb3I6IiwgZXJyKQogICAgfSBlbHNlIHsKICAgICAgICBmbXQuUHJpbnRsbigiUmVzdWx0YWRvOiIsIHJlc3VsdCkKICAgIH0KfQoKZnVuYyBkaXZpZGUoYSwgYiBpbnQpIGludCB7CiAgICBpZiBiID09IDAgewogICAgICAgIHBhbmljKCJkaXZpc2nDs24gcG9yIGNlcm8iKQogICAgfQogICAgcmV0dXJuIGEgLyBiCn0KCmZ1bmMgc2FmZURpdmlkZShhLCBiIGludCkgKHJlc3VsdCBpbnQsIGVyciBlcnJvcikgewogICAgZGVmZXIgZnVuYygpIHsKICAgICAgICBpZiByIDo9IHJlY292ZXIoKTsgciAhPSBuaWwgewogICAgICAgICAgICBlcnIgPSBlcnJvcnMuTmV3KGZtdC5TcHJpbnQocikpCiAgICAgICAgfQogICAgfSgpCiAgICByZXN1bHQgPSBkaXZpZGUoYSwgYikKICAgIHJldHVybgp9"))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>package main

import (
    &quot;errors&quot;
    &quot;fmt&quot;
)

func main() {
    result, err := safeDivide(10, 0)
    if err != nil {
        fmt.Println(&quot;Error:&quot;, err)
    } else {
        fmt.Println(&quot;Resultado:&quot;, result)
    }
}

func divide(a, b int) int {
    if b == 0 {
        panic(&quot;divisi&oacute;n por cero&quot;)
    }
    return a / b
}

func safeDivide(a, b int) (result int, err error) {
    defer func() {
        if r := recover(); r != nil {
            err = errors.New(fmt.Sprint(r))
        }
    }()
    result = divide(a, b)
    return
}</pre></div><div class='content'><p><strong>Explicación:</strong></p>
<ul>
<li>La función <code>divide</code> provoca un pánico si el divisor es cero.</li>
<li>La función <code>safeDivide</code> utiliza <code>defer</code> y <code>recover</code> para manejar el pánico y devolver un error en lugar de detener el programa.</li>
</ul>
</div><h2>Ejercicio 2: Implementación de un Servidor Web Seguro</h2>
<div class='content'><p>Escribe un servidor web simple que maneje las solicitudes HTTP. Si ocurre un pánico durante el manejo de una solicitud, el servidor debe recuperarse y devolver un mensaje de error al cliente en lugar de detenerse.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("cGFja2FnZSBtYWluCgppbXBvcnQgKAogICAgImZtdCIKICAgICJuZXQvaHR0cCIKKQoKZnVuYyBtYWluKCkgewogICAgaHR0cC5IYW5kbGVGdW5jKCIvIiwgc2FmZUhhbmRsZXIpCiAgICBmbXQuUHJpbnRsbigiU2Vydmlkb3IgZXNjdWNoYW5kbyBlbiBodHRwOi8vbG9jYWxob3N0OjgwODAiKQogICAgaHR0cC5MaXN0ZW5BbmRTZXJ2ZSgiOjgwODAiLCBuaWwpCn0KCmZ1bmMgc2FmZUhhbmRsZXIodyBodHRwLlJlc3BvbnNlV3JpdGVyLCByICpodHRwLlJlcXVlc3QpIHsKICAgIGRlZmVyIGZ1bmMoKSB7CiAgICAgICAgaWYgciA6PSByZWNvdmVyKCk7IHIgIT0gbmlsIHsKICAgICAgICAgICAgaHR0cC5FcnJvcih3LCAiT2N1cnJpw7MgdW4gZXJyb3IgaW50ZXJubyIsIGh0dHAuU3RhdHVzSW50ZXJuYWxTZXJ2ZXJFcnJvcikKICAgICAgICB9CiAgICB9KCkKICAgIGhhbmRsZXIodywgcikKfQoKZnVuYyBoYW5kbGVyKHcgaHR0cC5SZXNwb25zZVdyaXRlciwgciAqaHR0cC5SZXF1ZXN0KSB7CiAgICBwYW5pYygiwqFBbGdvIHNhbGnDsyBtYWwgZW4gZWwgc2Vydmlkb3IhIikKICAgIGZtdC5GcHJpbnRsbih3LCAiSG9sYSwgbXVuZG8iKQp9"))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>package main

import (
    &quot;fmt&quot;
    &quot;net/http&quot;
)

func main() {
    http.HandleFunc(&quot;/&quot;, safeHandler)
    fmt.Println(&quot;Servidor escuchando en http://localhost:8080&quot;)
    http.ListenAndServe(&quot;:8080&quot;, nil)
}

func safeHandler(w http.ResponseWriter, r *http.Request) {
    defer func() {
        if r := recover(); r != nil {
            http.Error(w, &quot;Ocurri&oacute; un error interno&quot;, http.StatusInternalServerError)
        }
    }()
    handler(w, r)
}

func handler(w http.ResponseWriter, r *http.Request) {
    panic(&quot;&iexcl;Algo sali&oacute; mal en el servidor!&quot;)
    fmt.Fprintln(w, &quot;Hola, mundo&quot;)
}</pre></div><div class='content'><p><strong>Explicación:</strong></p>
<ul>
<li>La función <code>safeHandler</code> utiliza <code>defer</code> y <code>recover</code> para manejar cualquier pánico que ocurra en <code>handler</code>.</li>
<li>Si <code>handler</code> provoca un pánico, <code>recover</code> captura el pánico y devuelve un mensaje de error al cliente.</li>
</ul>
</div><h1>Conclusión</h1>
<div class='content'><p>En esta sección, hemos aprendido sobre los mecanismos <code>panic</code> y <code>recover</code> en Go. <code>panic</code> se utiliza para manejar situaciones críticas donde la ejecución del programa no puede continuar normalmente, mientras que <code>recover</code> permite recuperar el control del programa y manejar el error de manera segura. Estos mecanismos son esenciales para escribir programas robustos y confiables en Go.</p>
<p>En el próximo módulo, exploraremos la concurrencia en Go, comenzando con las goroutines.</p>
</div><div class='row navigation'>
	<div class='col-2'>
					<a href='04-02-custom-errors' title="Errores Personalizados">&#x25C4;Anterior</a>
			</div>
	<div class='col-8 text-center'>
			</div>
	<div class='col-2 text-end'>
					<a href='05-01-goroutines' title="Goroutines">Siguiente &#x25BA;</a>
			</div>
</div>

			</div>
		</div>
		<div class="col-12 col-lg-4 publi" id="div_publi">
			<h1>Publicidad</h1>
			<p>Este espacio está destinado a publicidad.</p>
			<p>Si quieres ser patrocinador, contáctanos para incluir enlaces en esta zona: <a href='mailto:admin@campusempresa.cat'>admin@campusempresa.cat</a></p>
			<p>¡Gracias por colaborar!</p>
		</div>
	</div>
</div>

   <div class="container-xxl my-3">
	<div class="row">
		<div class="col">
			<footer>&copy; Copyright 2024. Todos los derechos reservados</footer>
		</div>
	</div>
</div>	

<div id="cookies_adv" style="display:none;">
	Fem servir galetes per millorar la teva experiència d'ús i oferir continguts adaptats als teus interessos
    <a href="#" id="btn_accept_cookies" class="button">Aceptar</a>
    <a href="/cookies">Mas información</a>
</div>	

	</div>    
</body>
</html>
