<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Introducción a las Excepciones</title>

    <link rel="alternate" href="https://campusempresa.com/mod/ruby/introduction-to-exceptions" hreflang="es" />
	<link rel="alternate" href="https://campusempresa.cat/mod/ruby/introduction-to-exceptions" hreflang="ca" />
	<link rel="alternate" href="https://enterprisecampus.net/mod/ruby/introduction-to-exceptions" hreflang="en" />
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
	<link href="/css/site.css" rel="stylesheet">
	
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  	<script type="text/javascript" src="js/math_init.js"></script>
  	<script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js"></script>
  	<script type="text/javascript" src="/js/cookie.js"></script>
  	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body  class="test" >
    <div id="content">
		<div id="header" class="container-xxl">
	<div class="row">
		<div class="col-8 p-0">
			<h1 class="m-0 p-0">
				<a href="/"><img src="/img/logo_header.png"></a>
			</h1>
		</div>
		<div class="col-4 p-0 text-end">
			<h2 id="main_title"><cite>Construyendo la sociedad de hoy y del mañana</cite></h2>
			<h3 id="main_subtitle"></h3>
		</div>
	</div>
</div>
<div class="container-xxl" style="margin-top: -1em;">
	<div class="row">
		<div class="col-12 p-0 m-0 text-end">
										<a href="https://enterprisecampus.net/mod/ruby/introduction-to-exceptions" class="px-2">EN</a></b>
				|
				<b class="px-2">ES</b>
				|
				<a href="https://campusempresa.cat/mod/ruby/introduction-to-exceptions" class="px-2">CA</a>
								</div>
	</div>
</div>
   <div class="top-bar container-fluid">
	<div class="container-xxl">
		<div class="row">
			<div class="col" id="left_menu">
				<a href="/objective">El Proyecto</a>
				<a href="/about">Sobre nosotros</a>
				<a href="/contribute">Contribuir</a>
				<a href="/donate">Donaciones</a>
				<a href="/licence">Licencia</a>
			</div>
		</div>
	</div>
   </div>

<div class="container-xxl" id="main_content">
	<div class="row">
		<div class="col-12 col-lg-8">
			<div id="nav1" class="navigation"></div>
			<div id="inner_content">
									<div class="assert">
						<p><b>Atención!</b> Ha habido un error en la generación del curso y puede contener errores de traducción.Estamos trabajando para solucinarlo por lo que se deben usar los contenidos con cuidado.Se puede consultar el contenido correcto en otro idioma en el siguiente enlace:<br>
						<a href="https://enterprisecampus.net/mod/ruby/introduction-to-exceptions">https://enterprisecampus.net/mod/ruby/introduction-to-exceptions</a></p>
					</div>
								<div class='row navigation'>
	<div class='col-4'>
					<a href='file-operations'>&#x25C4;Operaciones de Archivo</a>
			</div>
	<div class='col-4 text-center'>
		<a href="./" class="title">Introducción a las Excepciones</a>
	</div>
	<div class='col-4 text-end'>
					<a href='handling-exceptions'>Manejo de Excepciones &#x25BA;</a>
			</div>
</div>
<div class='content'></div><h1>¿Qué son las Excepciones?</h1>
<div class='content'><p>Las excepciones son eventos que pueden alterar el flujo normal de un programa. Se utilizan para manejar errores y otras condiciones excepcionales de manera controlada. En Ruby, las excepciones son objetos que representan estas condiciones de error.</p>
</div><h2>Conceptos Clave</h2>
<div class='content'><ul>
<li><strong>Manejo de Excepciones</strong>: El proceso de responder a la ocurrencia de excepciones.</li>
<li><strong>Raise</strong>: La acción de crear una excepción.</li>
<li><strong>Rescue</strong>: La acción de manejar una excepción.</li>
<li><strong>Ensure</strong>: Un bloque que siempre se ejecutará, independientemente de si se levantó una excepción o no.</li>
</ul>
</div><h1>Levantando Excepciones</h1>
<div class='content'><p>En Ruby, puedes levantar una excepción usando la palabra clave <code>raise</code>. Esto se puede hacer con o sin un argumento.</p>
</div><h2>Ejemplo: Levantando una Excepción</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("IyBMZXZhbnRhbmRvIHVuYSBleGNlcGNpw7NuIHNpbiB1biBhcmd1bWVudG8KcmFpc2UgIsKhSGEgb2N1cnJpZG8gdW4gZXJyb3IhIgoKIyBMZXZhbnRhbmRvIHVuYSBleGNlcGNpw7NuIGNvbiB1biB0aXBvIGVzcGVjw61maWNvCnJhaXNlIEFyZ3VtZW50RXJyb3IsICLCoUFyZ3VtZW50byBpbnbDoWxpZG8hIg=="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'># Levantando una excepci&oacute;n sin un argumento
raise &quot;&iexcl;Ha ocurrido un error!&quot;

# Levantando una excepci&oacute;n con un tipo espec&iacute;fico
raise ArgumentError, &quot;&iexcl;Argumento inv&aacute;lido!&quot;</pre></div><div class='content'></div><h1>Manejando Excepciones</h1>
<div class='content'><p>Para manejar excepciones, Ruby proporciona el bloque <code>begin-rescue</code>. Esto te permite capturar y gestionar excepciones de manera elegante.</p>
</div><h2>Ejemplo: Manejando una Excepción</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("YmVnaW4KICAjIEPDs2RpZ28gcXVlIHB1ZWRlIGxldmFudGFyIHVuYSBleGNlcGNpw7NuCiAgcmVzdWx0ID0gMTAgLyAwCnJlc2N1ZSBaZXJvRGl2aXNpb25FcnJvciA9PiBlCiAgIyBDw7NkaWdvIHBhcmEgbWFuZWphciBsYSBleGNlcGNpw7NuCiAgcHV0cyAiRXJyb3I6ICN7ZS5tZXNzYWdlfSIKZW5k"))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>begin
  # C&oacute;digo que puede levantar una excepci&oacute;n
  result = 10 / 0
rescue ZeroDivisionError =&gt; e
  # C&oacute;digo para manejar la excepci&oacute;n
  puts &quot;Error: #{e.message}&quot;
end</pre></div><div class='content'></div><h2>Explicación</h2>
<div class='content'><ul>
<li><strong>begin</strong>: Inicia el bloque de código donde pueden ocurrir excepciones.</li>
<li><strong>rescue</strong>: Define el bloque de código a ejecutar si se levanta una excepción.</li>
<li><strong>ZeroDivisionError</strong>: El tipo específico de excepción que se está rescatando.</li>
<li><strong>e</strong>: La variable que contiene el objeto de excepción.</li>
</ul>
</div><h1>Asegurando la Ejecución</h1>
<div class='content'><p>El bloque <code>ensure</code> se utiliza para garantizar que cierto código siempre se ejecute, independientemente de si se levantó una excepción o no.</p>
</div><h2>Ejemplo: Usando Ensure</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("YmVnaW4KICAjIEPDs2RpZ28gcXVlIHB1ZWRlIGxldmFudGFyIHVuYSBleGNlcGNpw7NuCiAgZmlsZSA9IEZpbGUub3BlbigiZXhhbXBsZS50eHQiLCAiciIpCiAgIyBSZWFsaXphciBvcGVyYWNpb25lcyBlbiBlbCBhcmNoaXZvCnJlc2N1ZSBFcnJubzo6RU5PRU5UID0+IGUKICAjIE1hbmVqYXIgbGEgZXhjZXBjacOzbiBkZSBhcmNoaXZvIG5vIGVuY29udHJhZG8KICBwdXRzICJBcmNoaXZvIG5vIGVuY29udHJhZG86ICN7ZS5tZXNzYWdlfSIKZW5zdXJlCiAgIyBBc2VndXJhciBxdWUgZWwgYXJjaGl2byBzZSBjaWVycmUKICBmaWxlLmNsb3NlIGlmIGZpbGUKZW5k"))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>begin
  # C&oacute;digo que puede levantar una excepci&oacute;n
  file = File.open(&quot;example.txt&quot;, &quot;r&quot;)
  # Realizar operaciones en el archivo
rescue Errno::ENOENT =&gt; e
  # Manejar la excepci&oacute;n de archivo no encontrado
  puts &quot;Archivo no encontrado: #{e.message}&quot;
ensure
  # Asegurar que el archivo se cierre
  file.close if file
end</pre></div><div class='content'></div><h1>Tipos Comunes de Excepciones</h1>
<div class='content'><p>Aquí hay algunas excepciones comunes que podrías encontrar en Ruby:</p>
<table>
<thead>
<tr>
<th>Tipo de Excepción</th>
<th>Descripción</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>StandardError</code></td>
<td>El predeterminado para la mayoría de los errores</td>
</tr>
<tr>
<td><code>ArgumentError</code></td>
<td>Se levanta cuando los argumentos son incorrectos</td>
</tr>
<tr>
<td><code>NoMethodError</code></td>
<td>Se levanta cuando no se encuentra un método</td>
</tr>
<tr>
<td><code>RuntimeError</code></td>
<td>Un error genérico levantado por <code>raise</code></td>
</tr>
<tr>
<td><code>ZeroDivisionError</code></td>
<td>Se levanta al dividir por cero</td>
</tr>
<tr>
<td><code>TypeError</code></td>
<td>Se levanta cuando un objeto es del tipo incorrecto</td>
</tr>
</tbody>
</table>
</div><h1>Excepciones Personalizadas</h1>
<div class='content'><p>Puedes definir tus propias excepciones creando una nueva clase que herede de <code>StandardError</code>.</p>
</div><h2>Ejemplo: Excepción Personalizada</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("Y2xhc3MgTXlDdXN0b21FcnJvciA8IFN0YW5kYXJkRXJyb3IKZW5kCgpiZWdpbgogICMgQ8OzZGlnbyBxdWUgcHVlZGUgbGV2YW50YXIgdW5hIGV4Y2VwY2nDs24gcGVyc29uYWxpemFkYQogIHJhaXNlIE15Q3VzdG9tRXJyb3IsICLCoUFsZ28gc2FsacOzIG1hbCEiCnJlc2N1ZSBNeUN1c3RvbUVycm9yID0+IGUKICAjIE1hbmVqYXIgbGEgZXhjZXBjacOzbiBwZXJzb25hbGl6YWRhCiAgcHV0cyAiRXJyb3IgcGVyc29uYWxpemFkbzogI3tlLm1lc3NhZ2V9IgplbmQ="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>class MyCustomError &lt; StandardError
end

begin
  # C&oacute;digo que puede levantar una excepci&oacute;n personalizada
  raise MyCustomError, &quot;&iexcl;Algo sali&oacute; mal!&quot;
rescue MyCustomError =&gt; e
  # Manejar la excepci&oacute;n personalizada
  puts &quot;Error personalizado: #{e.message}&quot;
end</pre></div><div class='content'></div><h1>Resumen</h1>
<div class='content'><ul>
<li>Las excepciones se utilizan para manejar errores y condiciones excepcionales en Ruby.</li>
<li>Usa <code>raise</code> para crear excepciones y <code>rescue</code> para manejarlas.</li>
<li>El bloque <code>ensure</code> garantiza que cierto código siempre se ejecute.</li>
<li>Ruby proporciona una variedad de tipos de excepciones integradas, y también puedes crear excepciones personalizadas.</li>
</ul>
<p>Al comprender y utilizar las excepciones, puedes hacer que tus programas en Ruby sean más robustos y resistentes a errores.</p>
</div><div class='row navigation'>
	<div class='col-4'>
					<a href='file-operations'>&#x25C4;Operaciones de Archivo</a>
			</div>
	<div class='col-4 text-center'>
		<a href="./" class="title">Introducción a las Excepciones</a>
	</div>
	<div class='col-4 text-end'>
					<a href='handling-exceptions'>Manejo de Excepciones &#x25BA;</a>
			</div>
</div>

			</div>
		</div>
		<div class="col-12 col-lg-4 publi" id="div_publi">
			<h1>Publicidad</h1>
			<p>Este espacio está destinado a publicidad.</p>
			<p>Si quieres ser patrocinador, contáctanos para incluir enlaces en esta zona: <a href='mailto:admin@campusempresa.cat'>admin@campusempresa.cat</a></p>
			<p>¡Gracias por colaborar!</p>
		</div>
	</div>
</div>

   <div class="container-xxl my-3">
	<div class="row">
		<div class="col">
			<footer>&copy; Copyright 2024. Todos los derechos reservados</footer>
		</div>
	</div>
</div>	

<div id="cookies_adv" style="display:none;">
	Fem servir galetes per millorar la teva experiència d'ús i oferir continguts adaptats als teus interessos
    <a href="#" id="btn_accept_cookies" class="button">Aceptar</a>
    <a href="/cookies">Mas información</a>
</div>	

	</div>    
</body>
</html>
