<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Excepciones Personalizadas</title>

    <link rel="alternate" href="https://campusempresa.com/es/python/custom-exceptions" hreflang="es" />
    <link rel="alternate" href="https://campusempresa.com/es/python/custom-exceptions" hreflang="x-default" />
	<link rel="alternate" href="https://campusempresa.com/ca/python/custom-exceptions" hreflang="ca" />
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
	<link href="/css/site.css" rel="stylesheet">
	
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  	<script type="text/javascript" src="js/math_init.js"></script>
  	<script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js"></script>
  	<script type="text/javascript" src="/js/cookie.js"></script>
  	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body>
    <div id="content">
		<div id="header" class="container-xxl">
	<div class="row">
		<div class="col-8 p-0">
			<h1 class="m-0 p-0">
				<a href="/es/"><img src="/img/logo_header.png" style="visibility:hiddenxx;"></a>
			</h1>
		</div>
		<div class="col-4 p-0 text-end">
			<h2 id="main_title"><cite>Construyendo la sociedad de hoy<br> y del mañana</cite></h2>
			<h3 id="main_subtitle"></h3>
		</div>
	</div>
</div>
<div class="container-xxl" style="margin-top: -1em;">
	<div class="row">
		<div class="col-12 p-0 m-0 text-end">
										<b id="lit_lang_es" class="px-2">ES</b>
				|
				<a href="/ca/python/custom-exceptions" id="lnk_lang_ca" data-lang="ca" class="px-2">CA</a>
					</div>
	</div>
</div>
   <div class="top-bar container-fluid">
	<div class="container-xxl">
		<div class="row">
			<div class="col" id="left_menu">
				<a href="objective">El Proyecto</a>
				<a href="about">Sobre nosotros</a>
				<a href="contribute">Contribuir</a>
				<a href="donate">Donaciones</a>
				<a href="licence">Licencia</a>
			</div>
		</div>
	</div>
   </div>

<div class="container-xxl" id="main_content">
	<div class="row">
		<div class="col-12 col-lg-8">
			<div id="nav1" class="navigation"></div>
			<div id="inner_content"><div class='content'></div><h1>Introducción</h1>
<div class='content'><p>En Python, las excepciones son una forma de manejar errores de manera elegante. Aunque Python proporciona muchas excepciones integradas, a veces necesitas crear tus propias excepciones personalizadas para manejar situaciones específicas en tu código. Esta sección te guiará a través del proceso de crear y usar excepciones personalizadas, desde niveles principiantes hasta avanzados.</p>
</div><h1>¿Por Qué Usar Excepciones Personalizadas?</h1>
<div class='content'><ul>
<li><strong>Especificidad</strong>: Las excepciones personalizadas te permiten manejar condiciones de error específicas en tu código.</li>
<li><strong>Legibilidad</strong>: Hacen que tu código sea más legible y mantenible al indicar claramente qué salió mal.</li>
<li><strong>Depuración</strong>: Las excepciones personalizadas pueden proporcionar mensajes de error más detallados, facilitando la depuración.</li>
</ul>
</div><h1>Creando una Excepción Personalizada Básica</h1>
<div class='content'><p>Crear una excepción personalizada en Python es sencillo. Simplemente defines una nueva clase que hereda de la clase integrada <code>Exception</code>.</p>
</div><h2>Ejemplo</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("Y2xhc3MgTXlDdXN0b21FcnJvcihFeGNlcHRpb24pOgogICAgIiIiRXhjZXBjacOzbiBsYW56YWRhIHBhcmEgY29uZGljaW9uZXMgZGUgZXJyb3IgcGVyc29uYWxpemFkYXMuIiIiCiAgICBwYXNzCgojIFVzbwp0cnk6CiAgICByYWlzZSBNeUN1c3RvbUVycm9yKCLCoUFsZ28gc2FsacOzIG1hbCEiKQpleGNlcHQgTXlDdXN0b21FcnJvciBhcyBlOgogICAgcHJpbnQoZSk="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>class MyCustomError(Exception):
    &quot;&quot;&quot;Excepci&oacute;n lanzada para condiciones de error personalizadas.&quot;&quot;&quot;
    pass

# Uso
try:
    raise MyCustomError(&quot;&iexcl;Algo sali&oacute; mal!&quot;)
except MyCustomError as e:
    print(e)</pre></div><div class='content'></div><h2>Explicación</h2>
<div class='content'><ul>
<li><strong>Definición de la Clase</strong>: <code>class MyCustomError(Exception):</code> define una nueva clase de excepción que hereda de <code>Exception</code>.</li>
<li><strong>Docstring</strong>: El docstring proporciona una descripción de la excepción.</li>
<li><strong>Lanzando la Excepción</strong>: <code>raise MyCustomError(&quot;¡Algo salió mal!&quot;)</code> lanza la excepción personalizada.</li>
<li><strong>Manejando la Excepción</strong>: El bloque <code>except MyCustomError as e</code> captura y maneja la excepción personalizada.</li>
</ul>
</div><h1>Añadiendo Más Funcionalidad</h1>
<div class='content'><p>Puedes añadir más funcionalidad a tus excepciones personalizadas sobrescribiendo el método <code>__init__</code> y añadiendo atributos personalizados.</p>
</div><h2>Ejemplo</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("Y2xhc3MgRGV0YWlsZWRFcnJvcihFeGNlcHRpb24pOgogICAgIiIiRXhjZXBjacOzbiBsYW56YWRhIHBhcmEgZXJyb3JlcyBjb24gbcOhcyBkZXRhbGxlcy4iIiIKICAgIAogICAgZGVmIF9faW5pdF9fKHNlbGYsIG1lc3NhZ2UsIGVycm9yX2NvZGUpOgogICAgICAgIHNlbGYubWVzc2FnZSA9IG1lc3NhZ2UKICAgICAgICBzZWxmLmVycm9yX2NvZGUgPSBlcnJvcl9jb2RlCiAgICAgICAgc3VwZXIoKS5fX2luaXRfXyhzZWxmLm1lc3NhZ2UpCgojIFVzbwp0cnk6CiAgICByYWlzZSBEZXRhaWxlZEVycm9yKCJPcGVyYWNpw7NuIGludsOhbGlkYSIsIDQwNCkKZXhjZXB0IERldGFpbGVkRXJyb3IgYXMgZToKICAgIHByaW50KGYiRXJyb3I6IHtlLm1lc3NhZ2V9LCBDw7NkaWdvOiB7ZS5lcnJvcl9jb2RlfSIp"))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>class DetailedError(Exception):
    &quot;&quot;&quot;Excepci&oacute;n lanzada para errores con m&aacute;s detalles.&quot;&quot;&quot;
    
    def __init__(self, message, error_code):
        self.message = message
        self.error_code = error_code
        super().__init__(self.message)

# Uso
try:
    raise DetailedError(&quot;Operaci&oacute;n inv&aacute;lida&quot;, 404)
except DetailedError as e:
    print(f&quot;Error: {e.message}, C&oacute;digo: {e.error_code}&quot;)</pre></div><div class='content'></div><h2>Explicación</h2>
<div class='content'><ul>
<li><strong>Atributos Personalizados</strong>: <code>self.message</code> y <code>self.error_code</code> almacenan información adicional sobre el error.</li>
<li><strong>Inicialización</strong>: <code>super().__init__(self.message)</code> llama al constructor de la clase base para inicializar la excepción.</li>
</ul>
</div><h1>Mejores Prácticas</h1>
<div class='content'><ul>
<li><strong>Nombres Significativos</strong>: Da a tus excepciones personalizadas nombres significativos que indiquen claramente la condición de error.</li>
<li><strong>Documentación</strong>: Siempre documenta tus excepciones personalizadas para explicar cuándo deben ser usadas.</li>
<li><strong>Herencia</strong>: Considera crear una clase base de excepción personalizada si tienes múltiples excepciones personalizadas relacionadas.</li>
</ul>
</div><h2>Ejemplo</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("Y2xhc3MgQmFzZUN1c3RvbUVycm9yKEV4Y2VwdGlvbik6CiAgICAiIiJDbGFzZSBiYXNlIHBhcmEgb3RyYXMgZXhjZXBjaW9uZXMgcGVyc29uYWxpemFkYXMiIiIKICAgIHBhc3MKCmNsYXNzIElucHV0RXJyb3IoQmFzZUN1c3RvbUVycm9yKToKICAgICIiIkV4Y2VwY2nDs24gbGFuemFkYSBwYXJhIGVudHJhZGEgaW52w6FsaWRhIiIiCiAgICBwYXNzCgpjbGFzcyBDYWxjdWxhdGlvbkVycm9yKEJhc2VDdXN0b21FcnJvcik6CiAgICAiIiJFeGNlcGNpw7NuIGxhbnphZGEgcGFyYSBlcnJvcmVzIGVuIGPDoWxjdWxvcyIiIgogICAgcGFzcw=="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>class BaseCustomError(Exception):
    &quot;&quot;&quot;Clase base para otras excepciones personalizadas&quot;&quot;&quot;
    pass

class InputError(BaseCustomError):
    &quot;&quot;&quot;Excepci&oacute;n lanzada para entrada inv&aacute;lida&quot;&quot;&quot;
    pass

class CalculationError(BaseCustomError):
    &quot;&quot;&quot;Excepci&oacute;n lanzada para errores en c&aacute;lculos&quot;&quot;&quot;
    pass</pre></div><div class='content'></div><h1>Uso Avanzado</h1>
<div class='content'><p>En escenarios más avanzados, podrías querer crear una jerarquía de excepciones personalizadas o integrarlas con mecanismos de registro.</p>
</div><h2>Ejemplo</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("aW1wb3J0IGxvZ2dpbmcKCmNsYXNzIEJhc2VDdXN0b21FcnJvcihFeGNlcHRpb24pOgogICAgIiIiQ2xhc2UgYmFzZSBwYXJhIG90cmFzIGV4Y2VwY2lvbmVzIHBlcnNvbmFsaXphZGFzIiIiCiAgICBwYXNzCgpjbGFzcyBJbnB1dEVycm9yKEJhc2VDdXN0b21FcnJvcik6CiAgICAiIiJFeGNlcGNpw7NuIGxhbnphZGEgcGFyYSBlbnRyYWRhIGludsOhbGlkYSIiIgogICAgCiAgICBkZWYgX19pbml0X18oc2VsZiwgbWVzc2FnZSk6CiAgICAgICAgc2VsZi5tZXNzYWdlID0gbWVzc2FnZQogICAgICAgIGxvZ2dpbmcuZXJyb3IoZiJJbnB1dEVycm9yOiB7c2VsZi5tZXNzYWdlfSIpCiAgICAgICAgc3VwZXIoKS5fX2luaXRfXyhzZWxmLm1lc3NhZ2UpCgojIFVzbwp0cnk6CiAgICByYWlzZSBJbnB1dEVycm9yKCJFbnRyYWRhIGRlIHVzdWFyaW8gaW52w6FsaWRhIikKZXhjZXB0IElucHV0RXJyb3IgYXMgZToKICAgIHByaW50KGUp"))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>import logging

class BaseCustomError(Exception):
    &quot;&quot;&quot;Clase base para otras excepciones personalizadas&quot;&quot;&quot;
    pass

class InputError(BaseCustomError):
    &quot;&quot;&quot;Excepci&oacute;n lanzada para entrada inv&aacute;lida&quot;&quot;&quot;
    
    def __init__(self, message):
        self.message = message
        logging.error(f&quot;InputError: {self.message}&quot;)
        super().__init__(self.message)

# Uso
try:
    raise InputError(&quot;Entrada de usuario inv&aacute;lida&quot;)
except InputError as e:
    print(e)</pre></div><div class='content'></div><h2>Explicación</h2>
<div class='content'><ul>
<li><strong>Registro</strong>: <code>logging.error(f&quot;InputError: {self.message}&quot;)</code> registra el mensaje de error.</li>
<li><strong>Herencia</strong>: <code>InputError</code> hereda de <code>BaseCustomError</code>, permitiendo una jerarquía estructurada de excepciones.</li>
</ul>
</div><h1>Conclusión</h1>
<div class='content'><p>Las excepciones personalizadas en Python proporcionan una forma poderosa de manejar condiciones de error específicas en tu código. Al crear excepciones personalizadas significativas y bien documentadas, puedes hacer que tu código sea más legible, mantenible y fácil de depurar. Ya seas un programador principiante o avanzado, entender cómo crear y usar excepciones personalizadas es una habilidad esencial en la programación con Python.</p>
</div></div>
		</div>
		<div class="col-12 col-lg-4 publi" id="div_publi">
			<h1>Publicidad</h1>
			<p>Este espacio está destinado a publicidad.</p>
			<p>Si quieres ser patrocinador, contáctanos para incluir enlaces en esta zona: <a href='mailto:admin@campusempresa.cat'>admin@campusempresa.cat</a></p>
			<p>¡Gracias por colaborar!</p>
		</div>
	</div>
</div>

   <div class="container-xxl my-3">
	<div class="row">
		<div class="col">
			<footer>&copy; Copyright 2024. Todos los derechos reservados</footer>
		</div>
	</div>
</div>	

<div id="cookies_adv" style="display:none;">
	Fem servir galetes per millorar la teva experiència d'ús i oferir continguts adaptats als teus interessos
    <a href="#" id="btn_accept_cookies" class="button">Entès!</a>
    <a href="cookies">Més informació</a>
</div>	

	</div>    
</body>
</html>
