<!DOCTYPE html>
<html lang="ca">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prova d'Excepcions</title>

    <link rel="alternate" href="https://campusempresa.com/es/junit/exception-testing" hreflang="es" />
    <link rel="alternate" href="https://campusempresa.com/es/junit/exception-testing" hreflang="x-default" />
	<link rel="alternate" href="https://campusempresa.com/ca/junit/exception-testing" hreflang="ca" />
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
	<link href="/css/site.css" rel="stylesheet">
	
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  	<script type="text/javascript" src="js/math_init.js"></script>
  	<script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js"></script>
  	<script type="text/javascript" src="/js/cookie.js"></script>
  	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body>
    <div id="content">
		<div id="header" class="container-xxl">
	<div class="row">
		<div class="col-8 p-0">
			<h1 class="m-0 p-0">
				<a href="/ca/"><img src="/img/logo_header.png" style="visibility:hiddenxx;"></a>
			</h1>
		</div>
		<div class="col-4 p-0 text-end">
			<h2 id="main_title"><cite>Construint la societat d'avui<br> i del demà</cite></h2>
			<h3 id="main_subtitle"></h3>
		</div>
	</div>
</div>
<div class="container-xxl" style="margin-top: -1em;">
	<div class="row">
		<div class="col-12 p-0 m-0 text-end">
							<a href="/es/junit/exception-testing" id="lnk_lang_es" data-lang="es" class="px-2">ES</a></b>
				|
				<b id="lit_lang_ca" class="px-2">CA</b>
								</div>
	</div>
</div>
   <div class="top-bar container-fluid">
	<div class="container-xxl">
		<div class="row">
			<div class="col" id="left_menu">
				<a href="objective">El Projecte</a>
				<a href="about">Sobre nosaltres</a>
				<a href="contribute">Contribuir</a>
				<a href="donate">Donacions</a>
				<a href="licence">Llicència</a>
			</div>
		</div>
	</div>
   </div>

<div class="container-xxl" id="main_content">
	<div class="row">
		<div class="col-12 col-lg-8">
			<div id="nav1" class="navigation"></div>
			<div id="inner_content"><div class='content'></div><h1>Introducció a la Prova d'Excepcions</h1>
<div class='content'><p>La prova d'excepcions és un aspecte crucial de les proves unitàries que assegura que el teu codi gestiona les condicions d'error de manera elegant. A JUnit, pots provar si el teu codi llança les excepcions esperades sota condicions específiques. Això ajuda a verificar la robustesa i la fiabilitat de la teva aplicació.</p>
</div><h1>Conceptes Clau</h1>
<div class='content'><ul>
<li><strong>Gestió d'Excepcions</strong>: Mecanisme per gestionar errors en temps d'execució, assegurant el flux normal de l'aplicació.</li>
<li><strong>Excepcions Esperades</strong>: Excepcions específiques que s'espera que el teu codi llanci sota certes condicions.</li>
<li><strong>Anotacions de JUnit</strong>: Marcadors especials a JUnit per especificar les excepcions esperades.</li>
</ul>
</div><h1>Prova d'Excepcions amb JUnit 4</h1>
<div class='content'><p>A JUnit 4, pots utilitzar l'anotació <code>@Test</code> amb el paràmetre <code>expected</code> per especificar l'excepció que esperes que una prova llanci.</p>
</div><h2>Exemple</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("aW1wb3J0IG9yZy5qdW5pdC5UZXN0OwppbXBvcnQgc3RhdGljIG9yZy5qdW5pdC5Bc3NlcnQuKjsKCnB1YmxpYyBjbGFzcyBFeGNlcHRpb25UZXN0IHsKCiAgICBAVGVzdChleHBlY3RlZCA9IElsbGVnYWxBcmd1bWVudEV4Y2VwdGlvbi5jbGFzcykKICAgIHB1YmxpYyB2b2lkIHRlc3RFeGNlcHRpb25Jc1Rocm93bigpIHsKICAgICAgICBNeUNsYXNzIG15Q2xhc3MgPSBuZXcgTXlDbGFzcygpOwogICAgICAgIG15Q2xhc3MubWV0aG9kVGhhdFRocm93c0V4Y2VwdGlvbigpOwogICAgfQp9"))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>import org.junit.Test;
import static org.junit.Assert.*;

public class ExceptionTest {

    @Test(expected = IllegalArgumentException.class)
    public void testExceptionIsThrown() {
        MyClass myClass = new MyClass();
        myClass.methodThatThrowsException();
    }
}</pre></div><div class='content'><p>En aquest exemple:</p>
<ul>
<li><code>@Test(expected = IllegalArgumentException.class)</code>: Aquesta anotació diu a JUnit que esperi una <code>IllegalArgumentException</code> quan es cridi <code>methodThatThrowsException</code>.</li>
<li>Si l'excepció es llança, la prova passa. Si no, la prova falla.</li>
</ul>
</div><h1>Prova d'Excepcions amb JUnit 5</h1>
<div class='content'><p>JUnit 5 introdueix el mètode <code>assertThrows</code>, que proporciona més flexibilitat i control sobre la prova d'excepcions.</p>
</div><h2>Exemple</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("aW1wb3J0IG9yZy5qdW5pdC5qdXBpdGVyLmFwaS5UZXN0OwppbXBvcnQgc3RhdGljIG9yZy5qdW5pdC5qdXBpdGVyLmFwaS5Bc3NlcnRpb25zLmFzc2VydFRocm93czsKCnB1YmxpYyBjbGFzcyBFeGNlcHRpb25UZXN0IHsKCiAgICBAVGVzdAogICAgcHVibGljIHZvaWQgdGVzdEV4Y2VwdGlvbklzVGhyb3duKCkgewogICAgICAgIE15Q2xhc3MgbXlDbGFzcyA9IG5ldyBNeUNsYXNzKCk7CiAgICAgICAgYXNzZXJ0VGhyb3dzKElsbGVnYWxBcmd1bWVudEV4Y2VwdGlvbi5jbGFzcywgKCkgLT4gewogICAgICAgICAgICBteUNsYXNzLm1ldGhvZFRoYXRUaHJvd3NFeGNlcHRpb24oKTsKICAgICAgICB9KTsKICAgIH0KfQ=="))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class ExceptionTest {

    @Test
    public void testExceptionIsThrown() {
        MyClass myClass = new MyClass();
        assertThrows(IllegalArgumentException.class, () -&gt; {
            myClass.methodThatThrowsException();
        });
    }
}</pre></div><div class='content'><p>En aquest exemple:</p>
<ul>
<li><code>assertThrows(IllegalArgumentException.class, () -&gt; { ... })</code>: Aquest mètode assegura que l'expressió lambda proporcionada llança una <code>IllegalArgumentException</code>.</li>
<li>Et permet capturar i inspeccionar l'excepció si cal.</li>
</ul>
</div><h1>Prova d'Excepcions Avançada</h1>
<div class='content'><p>Per a escenaris més avançats, potser necessitis verificar el missatge de l'excepció o altres propietats.</p>
</div><h2>Exemple</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("aW1wb3J0IG9yZy5qdW5pdC5qdXBpdGVyLmFwaS5UZXN0OwppbXBvcnQgc3RhdGljIG9yZy5qdW5pdC5qdXBpdGVyLmFwaS5Bc3NlcnRpb25zLio7CgpwdWJsaWMgY2xhc3MgQWR2YW5jZWRFeGNlcHRpb25UZXN0IHsKCiAgICBAVGVzdAogICAgcHVibGljIHZvaWQgdGVzdEV4Y2VwdGlvbk1lc3NhZ2UoKSB7CiAgICAgICAgTXlDbGFzcyBteUNsYXNzID0gbmV3IE15Q2xhc3MoKTsKICAgICAgICBFeGNlcHRpb24gZXhjZXB0aW9uID0gYXNzZXJ0VGhyb3dzKElsbGVnYWxBcmd1bWVudEV4Y2VwdGlvbi5jbGFzcywgKCkgLT4gewogICAgICAgICAgICBteUNsYXNzLm1ldGhvZFRoYXRUaHJvd3NFeGNlcHRpb24oKTsKICAgICAgICB9KTsKCiAgICAgICAgU3RyaW5nIGV4cGVjdGVkTWVzc2FnZSA9ICJJbnZhbGlkIGFyZ3VtZW50IjsKICAgICAgICBTdHJpbmcgYWN0dWFsTWVzc2FnZSA9IGV4Y2VwdGlvbi5nZXRNZXNzYWdlKCk7CgogICAgICAgIGFzc2VydFRydWUoYWN0dWFsTWVzc2FnZS5jb250YWlucyhleHBlY3RlZE1lc3NhZ2UpKTsKICAgIH0KfQ=="))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AdvancedExceptionTest {

    @Test
    public void testExceptionMessage() {
        MyClass myClass = new MyClass();
        Exception exception = assertThrows(IllegalArgumentException.class, () -&gt; {
            myClass.methodThatThrowsException();
        });

        String expectedMessage = &quot;Invalid argument&quot;;
        String actualMessage = exception.getMessage();

        assertTrue(actualMessage.contains(expectedMessage));
    }
}</pre></div><div class='content'><p>En aquest exemple:</p>
<ul>
<li>El mètode <code>assertThrows</code> captura l'excepció.</li>
<li>La prova després verifica que el missatge de l'excepció conté el text esperat.</li>
</ul>
</div><h1>Resum</h1>
<div class='content'><p>La prova d'excepcions és una part essencial de les proves unitàries que assegura que la teva aplicació gestiona els errors com s'espera. JUnit proporciona diferents maneres de provar excepcions:</p>
<ul>
<li>JUnit 4 utilitza l'anotació <code>@Test(expected = Exception.class)</code>.</li>
<li>JUnit 5 utilitza el mètode més flexible <code>assertThrows</code>.</li>
</ul>
<p>Dominant la prova d'excepcions, pots escriure codi més robust i fiable, assegurant que la teva aplicació es comporti correctament sota condicions d'error.</p>
</div></div>
		</div>
		<div class="col-12 col-lg-4 publi" id="div_publi">
			<h1>Publicitat</h1>
			<p>Aquest espai està destinat a publicitat.</p>
			<p>Si vols ser patrocinador, contacta amb nosaltres per incloure enllaços en aquesta zona: <a href='mailto:admin@campusempresa.cat'>admin@campusempresa.cat</a></p>
			<p>Gràcies per col·laborar!</p>
		</div>
	</div>
</div>

   <div class="container-xxl my-3">
	<div class="row">
		<div class="col">
			<footer>&copy; Copyright 2024. Tots els drets reservats</footer>
		</div>
	</div>
</div>	

<div id="cookies_adv" style="display:none;">
	Fem servir galetes per millorar la teva experiència d'ús i oferir continguts adaptats als teus interessos
    <a href="#" id="btn_accept_cookies" class="button">Entès!</a>
    <a href="cookies">Més informació</a>
</div>	

	</div>    
</body>
</html>
