<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manejo de Excepciones en Java</title>

    <link rel="alternate" href="https://campusempresa.com/mod/java/exception-handling" hreflang="es" />
	<link rel="alternate" href="https://campusempresa.cat/mod/java/exception-handling" hreflang="ca" />
	<link rel="alternate" href="https://enterprisecampus.net/mod/java/exception-handling" hreflang="en" />
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
	<link href="/css/site.css" rel="stylesheet">
	
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  	<script type="text/javascript" src="js/math_init.js"></script>
  	<script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js"></script>
  	<script type="text/javascript" src="/js/cookie.js"></script>
  	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body>
    <div id="content">
		<div id="header" class="container-xxl">
	<div class="row">
		<div class="col-8 p-0">
			<h1 class="m-0 p-0">
				<a href="/"><img src="/img/logo_header.png" style="visibility:hiddenxx;"></a>
			</h1>
		</div>
		<div class="col-4 p-0 text-end">
			<h2 id="main_title"><cite>Construyendo la sociedad de hoy y del mañana</cite></h2>
			<h3 id="main_subtitle"></h3>
		</div>
	</div>
</div>
<div class="container-xxl" style="margin-top: -1em;">
	<div class="row">
		<div class="col-12 p-0 m-0 text-end">
										<a href="https://enterprisecampus.net/mod/java/exception-handling" class="px-2">EN</a></b>
				|
				<b class="px-2">ES</b>
				|
				<a href="https://campusempresa.cat/mod/java/exception-handling" class="px-2">CA</a>
								</div>
	</div>
</div>
   <div class="top-bar container-fluid">
	<div class="container-xxl">
		<div class="row">
			<div class="col" id="left_menu">
				<a href="/objective">El Proyecto</a>
				<a href="/about">Sobre nosotros</a>
				<a href="/contribute">Contribuir</a>
				<a href="/donate">Donaciones</a>
				<a href="/licence">Licencia</a>
			</div>
		</div>
	</div>
   </div>

<div class="container-xxl" id="main_content">
	<div class="row">
		<div class="col-12 col-lg-8">
			<div id="nav1" class="navigation"></div>
			<div id="inner_content"><div class='row navigation'>
	<div class='col-4'>
					<a href='abstract-classes'>&#x25C4;Clases Abstractas</a>
			</div>
	<div class='col-4 text-center'>
		<a href="./" class="title">Manejo de Excepciones en Java</a>
	</div>
	<div class='col-4 text-end'>
					<a href='generics'>Genéricos &#x25BA;</a>
			</div>
</div>
<div class='content'></div><h1>Introducción al Manejo de Excepciones</h1>
<div class='content'><p>El manejo de excepciones es un mecanismo poderoso en Java para manejar errores en tiempo de ejecución, asegurando el flujo normal de la aplicación. Te permite gestionar errores de manera elegante y mantener la robustez de tu código.</p>
</div><h2>Conceptos Clave</h2>
<div class='content'><ul>
<li><strong>Excepción</strong>: Un evento que interrumpe el flujo normal del programa.</li>
<li><strong>Manejo de Excepciones</strong>: El proceso de responder a las excepciones cuando ocurren.</li>
<li><strong>Bloque Try-Catch</strong>: Un bloque de código utilizado para manejar excepciones.</li>
<li><strong>Bloque Finally</strong>: Un bloque que se ejecuta independientemente de si se lanza una excepción o no.</li>
<li><strong>Throw</strong>: Utilizado para lanzar explícitamente una excepción.</li>
<li><strong>Throws</strong>: Indica qué excepciones puede lanzar un método.</li>
</ul>
</div><h1>Tipos de Excepciones</h1>
<div class='content'><p>Las excepciones en Java se dividen en dos categorías principales:</p>
<ol>
<li><strong>Excepciones Comprobadas</strong>: Excepciones que se comprueban en tiempo de compilación.</li>
<li><strong>Excepciones No Comprobadas</strong>: Excepciones que se comprueban en tiempo de ejecución.</li>
</ol>
</div><h2>Ejemplos</h2>
<div class='content'><ul>
<li><strong>Excepción Comprobada</strong>: <code>IOException</code>, <code>SQLException</code></li>
<li><strong>Excepción No Comprobada</strong>: <code>ArithmeticException</code>, <code>NullPointerException</code></li>
</ul>
</div><h1>Manejo Básico de Excepciones</h1>
<h2>Bloque Try-Catch</h2>
<div class='content'><p>El bloque <code>try</code> contiene código que podría lanzar una excepción, y el bloque <code>catch</code> maneja la excepción.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("cHVibGljIGNsYXNzIEV4Y2VwdGlvbkV4YW1wbGUgewogICAgcHVibGljIHN0YXRpYyB2b2lkIG1haW4oU3RyaW5nW10gYXJncykgewogICAgICAgIHRyeSB7CiAgICAgICAgICAgIGludCBkaXZpZGVCeVplcm8gPSA1IC8gMDsKICAgICAgICB9IGNhdGNoIChBcml0aG1ldGljRXhjZXB0aW9uIGUpIHsKICAgICAgICAgICAgU3lzdGVtLm91dC5wcmludGxuKCJBcml0aG1ldGljRXhjZXB0aW9uIGNhdWdodDogIiArIGUuZ2V0TWVzc2FnZSgpKTsKICAgICAgICB9CiAgICB9Cn0="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>public class ExceptionExample {
    public static void main(String[] args) {
        try {
            int divideByZero = 5 / 0;
        } catch (ArithmeticException e) {
            System.out.println(&quot;ArithmeticException caught: &quot; + e.getMessage());
        }
    }
}</pre></div><div class='content'><p>En este ejemplo, dividir por cero lanza una <code>ArithmeticException</code>, que es capturada por el bloque <code>catch</code>.</p>
</div><h2>Bloque Finally</h2>
<div class='content'><p>El bloque <code>finally</code> siempre se ejecuta, independientemente de si se lanza una excepción o no.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("cHVibGljIGNsYXNzIEZpbmFsbHlFeGFtcGxlIHsKICAgIHB1YmxpYyBzdGF0aWMgdm9pZCBtYWluKFN0cmluZ1tdIGFyZ3MpIHsKICAgICAgICB0cnkgewogICAgICAgICAgICBpbnQgZGl2aWRlQnlaZXJvID0gNSAvIDA7CiAgICAgICAgfSBjYXRjaCAoQXJpdGhtZXRpY0V4Y2VwdGlvbiBlKSB7CiAgICAgICAgICAgIFN5c3RlbS5vdXQucHJpbnRsbigiQXJpdGhtZXRpY0V4Y2VwdGlvbiBjYXVnaHQ6ICIgKyBlLmdldE1lc3NhZ2UoKSk7CiAgICAgICAgfSBmaW5hbGx5IHsKICAgICAgICAgICAgU3lzdGVtLm91dC5wcmludGxuKCJUaGlzIGlzIHRoZSBmaW5hbGx5IGJsb2NrLiIpOwogICAgICAgIH0KICAgIH0KfQ=="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>public class FinallyExample {
    public static void main(String[] args) {
        try {
            int divideByZero = 5 / 0;
        } catch (ArithmeticException e) {
            System.out.println(&quot;ArithmeticException caught: &quot; + e.getMessage());
        } finally {
            System.out.println(&quot;This is the finally block.&quot;);
        }
    }
}</pre></div><div class='content'><p>Aquí, el bloque <code>finally</code> se ejecutará incluso después de que se capture la excepción.</p>
</div><h1>Manejo Avanzado de Excepciones</h1>
<h2>Lanzar Excepciones</h2>
<div class='content'><p>Puedes lanzar una excepción usando la palabra clave <code>throw</code>.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("cHVibGljIGNsYXNzIFRocm93RXhhbXBsZSB7CiAgICBwdWJsaWMgc3RhdGljIHZvaWQgbWFpbihTdHJpbmdbXSBhcmdzKSB7CiAgICAgICAgdHJ5IHsKICAgICAgICAgICAgY2hlY2tBZ2UoMTUpOwogICAgICAgIH0gY2F0Y2ggKEV4Y2VwdGlvbiBlKSB7CiAgICAgICAgICAgIFN5c3RlbS5vdXQucHJpbnRsbigiRXhjZXB0aW9uIGNhdWdodDogIiArIGUuZ2V0TWVzc2FnZSgpKTsKICAgICAgICB9CiAgICB9CgogICAgc3RhdGljIHZvaWQgY2hlY2tBZ2UoaW50IGFnZSkgdGhyb3dzIEV4Y2VwdGlvbiB7CiAgICAgICAgaWYgKGFnZSA8IDE4KSB7CiAgICAgICAgICAgIHRocm93IG5ldyBFeGNlcHRpb24oIkFnZSBpcyBsZXNzIHRoYW4gMTgiKTsKICAgICAgICB9CiAgICB9Cn0="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>public class ThrowExample {
    public static void main(String[] args) {
        try {
            checkAge(15);
        } catch (Exception e) {
            System.out.println(&quot;Exception caught: &quot; + e.getMessage());
        }
    }

    static void checkAge(int age) throws Exception {
        if (age &lt; 18) {
            throw new Exception(&quot;Age is less than 18&quot;);
        }
    }
}</pre></div><div class='content'><p>En este ejemplo, si la edad es menor de 18, se lanza una excepción.</p>
</div><h2>Palabra Clave Throws</h2>
<div class='content'><p>La palabra clave <code>throws</code> se usa en las firmas de los métodos para declarar que un método puede lanzar excepciones.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("cHVibGljIGNsYXNzIFRocm93c0V4YW1wbGUgewogICAgcHVibGljIHN0YXRpYyB2b2lkIG1haW4oU3RyaW5nW10gYXJncykgewogICAgICAgIHRyeSB7CiAgICAgICAgICAgIGNoZWNrRmlsZSgpOwogICAgICAgIH0gY2F0Y2ggKElPRXhjZXB0aW9uIGUpIHsKICAgICAgICAgICAgU3lzdGVtLm91dC5wcmludGxuKCJJT0V4Y2VwdGlvbiBjYXVnaHQ6ICIgKyBlLmdldE1lc3NhZ2UoKSk7CiAgICAgICAgfQogICAgfQoKICAgIHN0YXRpYyB2b2lkIGNoZWNrRmlsZSgpIHRocm93cyBJT0V4Y2VwdGlvbiB7CiAgICAgICAgRmlsZVJlYWRlciBmaWxlID0gbmV3IEZpbGVSZWFkZXIoIm5vbmV4aXN0ZW50ZmlsZS50eHQiKTsKICAgIH0KfQ=="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>public class ThrowsExample {
    public static void main(String[] args) {
        try {
            checkFile();
        } catch (IOException e) {
            System.out.println(&quot;IOException caught: &quot; + e.getMessage());
        }
    }

    static void checkFile() throws IOException {
        FileReader file = new FileReader(&quot;nonexistentfile.txt&quot;);
    }
}</pre></div><div class='content'><p>Aquí, el método <code>checkFile</code> declara que puede lanzar una <code>IOException</code>.</p>
</div><h1>Excepciones Personalizadas</h1>
<div class='content'><p>Puedes crear tus propias excepciones extendiendo la clase <code>Exception</code>.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("Y2xhc3MgQ3VzdG9tRXhjZXB0aW9uIGV4dGVuZHMgRXhjZXB0aW9uIHsKICAgIHB1YmxpYyBDdXN0b21FeGNlcHRpb24oU3RyaW5nIG1lc3NhZ2UpIHsKICAgICAgICBzdXBlcihtZXNzYWdlKTsKICAgIH0KfQoKcHVibGljIGNsYXNzIEN1c3RvbUV4Y2VwdGlvbkV4YW1wbGUgewogICAgcHVibGljIHN0YXRpYyB2b2lkIG1haW4oU3RyaW5nW10gYXJncykgewogICAgICAgIHRyeSB7CiAgICAgICAgICAgIHZhbGlkYXRlKDE1KTsKICAgICAgICB9IGNhdGNoIChDdXN0b21FeGNlcHRpb24gZSkgewogICAgICAgICAgICBTeXN0ZW0ub3V0LnByaW50bG4oIkN1c3RvbUV4Y2VwdGlvbiBjYXVnaHQ6ICIgKyBlLmdldE1lc3NhZ2UoKSk7CiAgICAgICAgfQogICAgfQoKICAgIHN0YXRpYyB2b2lkIHZhbGlkYXRlKGludCBhZ2UpIHRocm93cyBDdXN0b21FeGNlcHRpb24gewogICAgICAgIGlmIChhZ2UgPCAxOCkgewogICAgICAgICAgICB0aHJvdyBuZXcgQ3VzdG9tRXhjZXB0aW9uKCJBZ2UgaXMgbGVzcyB0aGFuIDE4Iik7CiAgICAgICAgfQogICAgfQp9"))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>class CustomException extends Exception {
    public CustomException(String message) {
        super(message);
    }
}

public class CustomExceptionExample {
    public static void main(String[] args) {
        try {
            validate(15);
        } catch (CustomException e) {
            System.out.println(&quot;CustomException caught: &quot; + e.getMessage());
        }
    }

    static void validate(int age) throws CustomException {
        if (age &lt; 18) {
            throw new CustomException(&quot;Age is less than 18&quot;);
        }
    }
}</pre></div><div class='content'><p>En este ejemplo, se crea y lanza una excepción personalizada <code>CustomException</code> si la edad es menor de 18.</p>
</div><h1>Mejores Prácticas</h1>
<div class='content'><ul>
<li>Siempre captura la excepción más específica primero.</li>
<li>Evita capturar <code>Exception</code> a menos que sea necesario.</li>
<li>Limpia los recursos en el bloque <code>finally</code>.</li>
<li>Documenta las excepciones que tus métodos pueden lanzar usando la palabra clave <code>throws</code>.</li>
</ul>
</div><h1>Conclusión</h1>
<div class='content'><p>El manejo de excepciones es un aspecto crucial de la programación en Java. Te permite gestionar errores de manera elegante y asegurar la robustez de tus aplicaciones. Al entender y aplicar los conceptos de bloques try-catch, bloques finally, lanzar excepciones y crear excepciones personalizadas, puedes escribir código más confiable y mantenible.</p>
</div><div class='row navigation'>
	<div class='col-4'>
					<a href='abstract-classes'>&#x25C4;Clases Abstractas</a>
			</div>
	<div class='col-4 text-center'>
		<a href="./" class="title">Manejo de Excepciones en Java</a>
	</div>
	<div class='col-4 text-end'>
					<a href='generics'>Genéricos &#x25BA;</a>
			</div>
</div>
</div>
		</div>
		<div class="col-12 col-lg-4 publi" id="div_publi">
			<h1>Publicidad</h1>
			<p>Este espacio está destinado a publicidad.</p>
			<p>Si quieres ser patrocinador, contáctanos para incluir enlaces en esta zona: <a href='mailto:admin@campusempresa.cat'>admin@campusempresa.cat</a></p>
			<p>¡Gracias por colaborar!</p>
		</div>
	</div>
</div>

   <div class="container-xxl my-3">
	<div class="row">
		<div class="col">
			<footer>&copy; Copyright 2024. Todos los derechos reservados</footer>
		</div>
	</div>
</div>	

<div id="cookies_adv" style="display:none;">
	Fem servir galetes per millorar la teva experiència d'ús i oferir continguts adaptats als teus interessos
    <a href="#" id="btn_accept_cookies" class="button">Aceptar</a>
    <a href="/cookies">Mas información</a>
</div>	

	</div>    
</body>
</html>
