<!DOCTYPE html>
<html lang="ca">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestió d'Excepcions a Scala</title>

    <link rel="alternate" href="https://campusempresa.com/es/scala/exception-handling" hreflang="es" />
    <link rel="alternate" href="https://campusempresa.com/es/scala/exception-handling" hreflang="x-default" />
	<link rel="alternate" href="https://campusempresa.com/ca/scala/exception-handling" hreflang="ca" />
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
	<link href="/css/site.css" rel="stylesheet">
	
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  	<script type="text/javascript" src="js/math_init.js"></script>
  	<script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js"></script>
  	<script type="text/javascript" src="/js/cookie.js"></script>
  	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body>
    <div id="content">
		<div id="header" class="container-xxl">
	<div class="row">
		<div class="col-8 p-0">
			<h1 class="m-0 p-0">
				<a href="/ca/"><img src="/img/logo_header.png" style="visibility:hiddenxx;"></a>
			</h1>
		</div>
		<div class="col-4 p-0 text-end">
			<h2 id="main_title"><cite>Construint la societat d'avui<br> i del demà</cite></h2>
			<h3 id="main_subtitle"></h3>
		</div>
	</div>
</div>
<div class="container-xxl" style="margin-top: -1em;">
	<div class="row">
		<div class="col-12 p-0 m-0 text-end">
							<a href="/es/scala/exception-handling" id="lnk_lang_es" data-lang="es" class="px-2">ES</a></b>
				|
				<b id="lit_lang_ca" class="px-2">CA</b>
								</div>
	</div>
</div>
   <div class="top-bar container-fluid">
	<div class="container-xxl">
		<div class="row">
			<div class="col" id="left_menu">
				<a href="objective">El Projecte</a>
				<a href="about">Sobre nosaltres</a>
				<a href="contribute">Contribuir</a>
				<a href="donate">Donacions</a>
				<a href="licence">Llicència</a>
			</div>
		</div>
	</div>
   </div>

<div class="container-xxl" id="main_content">
	<div class="row">
		<div class="col-12 col-lg-8">
			<div id="nav1" class="navigation"></div>
			<div id="inner_content"><div class='content'><p>La gestió d'excepcions és un aspecte crucial de la programació que permet als desenvolupadors gestionar i respondre als errors en temps d'execució de manera elegant. A Scala, la gestió d'excepcions és similar a Java però amb algunes millores específiques de Scala. Aquesta secció et guiarà des dels conceptes bàsics fins als avançats de la gestió d'excepcions a Scala.</p>
</div><h1>Introducció a les Excepcions</h1>
<div class='content'><ul>
<li><strong>Definició</strong>: Una excepció és un esdeveniment que interromp el flux normal de l'execució d'un programa.</li>
<li><strong>Excepcions Comunes</strong>: <code>NullPointerException</code>, <code>ArrayIndexOutOfBoundsException</code>, <code>ArithmeticException</code>, etc.</li>
</ul>
</div><h1>Gestió Bàsica d'Excepcions</h1>
<h2>Bloc Try-Catch</h2>
<div class='content'><p>Scala utilitza un bloc <code>try-catch</code> per gestionar excepcions.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("dHJ5IHsKICAvLyBDb2RpIHF1ZSBwb2RyaWEgbGxhbsOnYXIgdW5hIGV4Y2VwY2nDswogIHZhbCByZXN1bHQgPSAxMCAvIDAKfSBjYXRjaCB7CiAgY2FzZSBlOiBBcml0aG1ldGljRXhjZXB0aW9uID0+IHByaW50bG4oIlMnaGEgY2FwdHVyYXQgdW5hIGV4Y2VwY2nDsyBhcml0bcOodGljYTogIiArIGUuZ2V0TWVzc2FnZSkKfQ=="))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>try {
  // Codi que podria llan&ccedil;ar una excepci&oacute;
  val result = 10 / 0
} catch {
  case e: ArithmeticException =&gt; println(&quot;S'ha capturat una excepci&oacute; aritm&egrave;tica: &quot; + e.getMessage)
}</pre></div><div class='content'><ul>
<li><strong>Explicació</strong>: El bloc <code>try</code> conté codi que podria llançar una excepció. El bloc <code>catch</code> captura excepcions específiques i les gestiona.</li>
</ul>
</div><h2>Blocs Catch Múltiples</h2>
<div class='content'><p>Pots capturar múltiples excepcions utilitzant múltiples declaracions <code>case</code>.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("dHJ5IHsKICB2YWwgYXJyID0gQXJyYXkoMSwgMiwgMykKICBwcmludGxuKGFycig1KSkKfSBjYXRjaCB7CiAgY2FzZSBlOiBBcnJheUluZGV4T3V0T2ZCb3VuZHNFeGNlcHRpb24gPT4gcHJpbnRsbigiw41uZGV4IGRlIGwnYXJyYXkgZm9yYSBkZSBsw61taXRzOiAiICsgZS5nZXRNZXNzYWdlKQogIGNhc2UgZTogRXhjZXB0aW9uID0+IHByaW50bG4oIkV4Y2VwY2nDsyBnZW5lcmFsOiAiICsgZS5nZXRNZXNzYWdlKQp9"))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>try {
  val arr = Array(1, 2, 3)
  println(arr(5))
} catch {
  case e: ArrayIndexOutOfBoundsException =&gt; println(&quot;&Iacute;ndex de l'array fora de l&iacute;mits: &quot; + e.getMessage)
  case e: Exception =&gt; println(&quot;Excepci&oacute; general: &quot; + e.getMessage)
}</pre></div><div class='content'><ul>
<li><strong>Explicació</strong>: El primer bloc <code>case</code> que coincideixi s'executa. Si no es troba cap coincidència, l'excepció es propaga.</li>
</ul>
</div><h1>Bloc Finally</h1>
<div class='content'><p>El bloc <code>finally</code> conté codi que sempre s'executarà, independentment de si s'ha llançat una excepció o no.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("dHJ5IHsKICB2YWwgcmVzdWx0ID0gMTAgLyAwCn0gY2F0Y2ggewogIGNhc2UgZTogQXJpdGhtZXRpY0V4Y2VwdGlvbiA9PiBwcmludGxuKCJTJ2hhIGNhcHR1cmF0IHVuYSBleGNlcGNpw7MgYXJpdG3DqHRpY2E6ICIgKyBlLmdldE1lc3NhZ2UpCn0gZmluYWxseSB7CiAgcHJpbnRsbigiQWl4w7Igc2VtcHJlIHMnZXhlY3V0YXLDoC4iKQp9"))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>try {
  val result = 10 / 0
} catch {
  case e: ArithmeticException =&gt; println(&quot;S'ha capturat una excepci&oacute; aritm&egrave;tica: &quot; + e.getMessage)
} finally {
  println(&quot;Aix&ograve; sempre s'executar&agrave;.&quot;)
}</pre></div><div class='content'><ul>
<li><strong>Explicació</strong>: El bloc <code>finally</code> és útil per a activitats de neteja com tancar fitxers o alliberar recursos.</li>
</ul>
</div><h1>Gestió Avançada d'Excepcions</h1>
<h2>Llançar Excepcions</h2>
<div class='content'><p>Pots llançar excepcions utilitzant la paraula clau <code>throw</code>.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("ZGVmIHZhbGlkYXRlQWdlKGFnZTogSW50KTogVW5pdCA9IHsKICBpZiAoYWdlIDwgMTgpIHsKICAgIHRocm93IG5ldyBJbGxlZ2FsQXJndW1lbnRFeGNlcHRpb24oIkwnZWRhdCBoYSBkZSBzZXIgMTggbyBtw6lzIikKICB9Cn0KCnRyeSB7CiAgdmFsaWRhdGVBZ2UoMTYpCn0gY2F0Y2ggewogIGNhc2UgZTogSWxsZWdhbEFyZ3VtZW50RXhjZXB0aW9uID0+IHByaW50bG4oIlMnaGEgY2FwdHVyYXQgdW5hIGV4Y2VwY2nDsyBkJ2FyZ3VtZW50IGlswrdsZWdhbDogIiArIGUuZ2V0TWVzc2FnZSkKfQ=="))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>def validateAge(age: Int): Unit = {
  if (age &lt; 18) {
    throw new IllegalArgumentException(&quot;L'edat ha de ser 18 o m&eacute;s&quot;)
  }
}

try {
  validateAge(16)
} catch {
  case e: IllegalArgumentException =&gt; println(&quot;S'ha capturat una excepci&oacute; d'argument il&middot;legal: &quot; + e.getMessage)
}</pre></div><div class='content'><ul>
<li><strong>Explicació</strong>: La paraula clau <code>throw</code> s'utilitza per llançar explícitament una excepció.</li>
</ul>
</div><h2>Excepcions Personalitzades</h2>
<div class='content'><p>Pots definir les teves pròpies excepcions estenent la classe <code>Exception</code>.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("Y2xhc3MgQ3VzdG9tRXhjZXB0aW9uKG1lc3NhZ2U6IFN0cmluZykgZXh0ZW5kcyBFeGNlcHRpb24obWVzc2FnZSkKCmRlZiByaXNreU1ldGhvZCgpOiBVbml0ID0gewogIHRocm93IG5ldyBDdXN0b21FeGNlcHRpb24oIkFxdWVzdGEgw6lzIHVuYSBleGNlcGNpw7MgcGVyc29uYWxpdHphZGEiKQp9Cgp0cnkgewogIHJpc2t5TWV0aG9kKCkKfSBjYXRjaCB7CiAgY2FzZSBlOiBDdXN0b21FeGNlcHRpb24gPT4gcHJpbnRsbigiUydoYSBjYXB0dXJhdCB1bmEgZXhjZXBjacOzIHBlcnNvbmFsaXR6YWRhOiAiICsgZS5nZXRNZXNzYWdlKQp9"))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>class CustomException(message: String) extends Exception(message)

def riskyMethod(): Unit = {
  throw new CustomException(&quot;Aquesta &eacute;s una excepci&oacute; personalitzada&quot;)
}

try {
  riskyMethod()
} catch {
  case e: CustomException =&gt; println(&quot;S'ha capturat una excepci&oacute; personalitzada: &quot; + e.getMessage)
}</pre></div><div class='content'><ul>
<li><strong>Explicació</strong>: Les excepcions personalitzades proporcionen informació d'error més específica.</li>
</ul>
</div><h2>Try, Success, and Failure</h2>
<div class='content'><p>Scala proporciona un enfocament més funcional per a la gestió d'excepcions utilitzant <code>Try</code>, <code>Success</code>, i <code>Failure</code>.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("aW1wb3J0IHNjYWxhLnV0aWwue1RyeSwgU3VjY2VzcywgRmFpbHVyZX0KCmRlZiBkaXZpZGUoYTogSW50LCBiOiBJbnQpOiBUcnlbSW50XSA9IFRyeShhIC8gYikKCnZhbCByZXN1bHQgPSBkaXZpZGUoMTAsIDApCgpyZXN1bHQgbWF0Y2ggewogIGNhc2UgU3VjY2Vzcyh2YWx1ZSkgPT4gcHJpbnRsbigiUmVzdWx0YXQ6ICIgKyB2YWx1ZSkKICBjYXNlIEZhaWx1cmUoZXhjZXB0aW9uKSA9PiBwcmludGxuKCJTJ2hhIGNhcHR1cmF0IHVuYSBleGNlcGNpw7M6ICIgKyBleGNlcHRpb24uZ2V0TWVzc2FnZSkKfQ=="))));alert("Copiat!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>import scala.util.{Try, Success, Failure}

def divide(a: Int, b: Int): Try[Int] = Try(a / b)

val result = divide(10, 0)

result match {
  case Success(value) =&gt; println(&quot;Resultat: &quot; + value)
  case Failure(exception) =&gt; println(&quot;S'ha capturat una excepci&oacute;: &quot; + exception.getMessage)
}</pre></div><div class='content'><ul>
<li><strong>Explicació</strong>: <code>Try</code> embolcalla un càlcul que podria llançar una excepció. <code>Success</code> i <code>Failure</code> representen el resultat.</li>
</ul>
</div><h1>Resum</h1>
<div class='content'><ul>
<li><strong>Try-Catch-Finally</strong>: Estructura bàsica per gestionar excepcions.</li>
<li><strong>Blocs Catch Múltiples</strong>: Captura diferents tipus d'excepcions.</li>
<li><strong>Llançar Excepcions</strong>: Llança explícitament excepcions quan sigui necessari.</li>
<li><strong>Excepcions Personalitzades</strong>: Crea els teus propis tipus d'excepcions per a una gestió d'errors específica.</li>
<li><strong>Enfocament Funcional</strong>: Utilitza <code>Try</code>, <code>Success</code>, i <code>Failure</code> per a un estil més funcional de gestió d'excepcions.</li>
</ul>
<p>Entendre i utilitzar efectivament la gestió d'excepcions a Scala farà que el teu codi sigui més robust i fàcil de mantenir. Practica aquests conceptes amb diversos exemples per obtenir una comprensió sòlida de la gestió d'excepcions a Scala.</p>
</div></div>
		</div>
		<div class="col-12 col-lg-4 publi" id="div_publi">
			<h1>Publicitat</h1>
			<p>Aquest espai està destinat a publicitat.</p>
			<p>Si vols ser patrocinador, contacta amb nosaltres per incloure enllaços en aquesta zona: <a href='mailto:admin@campusempresa.cat'>admin@campusempresa.cat</a></p>
			<p>Gràcies per col·laborar!</p>
		</div>
	</div>
</div>

   <div class="container-xxl my-3">
	<div class="row">
		<div class="col">
			<footer>&copy; Copyright 2024. Tots els drets reservats</footer>
		</div>
	</div>
</div>	

<div id="cookies_adv" style="display:none;">
	Fem servir galetes per millorar la teva experiència d'ús i oferir continguts adaptats als teus interessos
    <a href="#" id="btn_accept_cookies" class="button">Entès!</a>
    <a href="cookies">Més informació</a>
</div>	

	</div>    
</body>
</html>
